import Link from "next/link";
import { Button } from "@/components/shadcn/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/shadcn/collapsible";
import { Banknote, BadgeCheck, CreditCard } from "lucide-react";
import { RefundStatusTag } from "@/components/refunds/status";
import { Notice } from "@/components/ui-kit/notice";
import { RefundFinanceActions } from "@/components/refunds/finance-actions";
import { RefundRequestForm } from "@/components/refunds/request-form";
import { RefundReceipts } from "@/components/refunds/receipts";
import { editableRefund, euros, paymentMethods, refundActions, refundNumber, refundServices, type RefundActor, type RefundDetail as Detail } from "@/lib/refunds/types";
import { formatDate, formatDateTime, parseDateOnly } from "@/lib/format";

export function RefundDetail({ data, who, sites }: { data: Detail; who: RefundActor; sites: { id: string; name: string }[] }) {
  const row = data.request, editable = editableRefund(row, who);
  const query = row.status === 'NEEDS_INFORMATION' ? [...data.events].reverse().find(event => event.action === 'information') : undefined;
  const facts = [
    ['Customer', row.customerName || 'Not entered'], ['Site', row.clubName], ['Service', refundServices[row.service]],
    ['Member number', row.memberNumber || 'Not provided'], ['Contact email', row.contactEmail || 'Not provided'], ['Contact phone', row.contactPhone || 'Not provided'],
    ['Original payment date', row.paymentDate ? formatDate(parseDateOnly(row.paymentDate)) : 'Not entered'], ['Original payment reference', row.paymentReference || 'Not entered'],
    ['Submitted by', row.creatorName], ['Finance handler', row.handlerName || 'Unassigned'],
  ];
  return <div className="space-y-6">
    <div className="refund-heading"><div className="space-y-2"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight tabular-nums">{refundNumber(row.number)}</h1><RefundStatusTag status={row.status} /></div><p className="break-words text-sm text-ui-muted-foreground">{row.customerName || 'New customer refund'} · {row.clubName}</p></div><Button asChild variant="outline" className="min-h-11"><Link href="/refunds">Back to requests</Link></Button></div>
    <dl className="refund-summary grid sm:grid-cols-3"><div><dt><Banknote aria-hidden="true" />Requested</dt><dd>{euros(row.requestedCents)}</dd></div><div><dt><BadgeCheck aria-hidden="true" />Approved</dt><dd className={row.approvedCents === null ? 'refund-summary-text' : undefined}>{row.approvedCents === null ? 'Pending' : euros(row.approvedCents)}</dd>{row.approvedByName && <p className="mt-1 text-xs text-ui-muted-foreground">By {row.approvedByName}</p>}</div><div><dt><CreditCard aria-hidden="true" />Payment</dt><dd className="refund-summary-text">{row.status === 'REFUNDED' ? `Recorded ${row.paidOn ? formatDate(parseDateOnly(row.paidOn)) : ''}` : row.status === 'APPROVED' ? 'Awaiting external payment' : 'Not recorded'}</dd></div></dl>
    {query && <Notice tone="warning" title="Finance needs more information" description={query.note} />}
    <div className="refund-detail-columns items-start"><div className="min-w-0 space-y-6">
      {editable ? <RefundRequestForm id={row.id} row={row} sites={sites} /> : <section className="refund-panel space-y-5" aria-labelledby="request-details"><h2 id="request-details" className="text-lg font-semibold">Request details</h2><dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{facts.map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs text-ui-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value}</dd></div>)}</dl><div><h3 className="text-sm font-medium">Service description</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed">{row.description || 'Not entered'}</p></div><div><h3 className="text-sm font-medium">Refund reason</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed">{row.reason || 'Not entered'}</p></div></section>}
      {row.status === 'REFUNDED' && <section className="refund-panel space-y-3"><h2 className="text-lg font-semibold">External payment record</h2><p className="text-sm">{euros(row.approvedCents)} · {paymentMethods[row.paidMethod as keyof typeof paymentMethods] || row.paidMethod}</p><p className="break-words text-sm">Reference: {row.paidReference}</p><p className="text-sm text-ui-muted-foreground">Recorded by {row.paidByName}. The payment was made outside Turnfin.</p></section>}
      <div className="refund-panel"><RefundReceipts id={row.id} version={row.version} attachments={data.attachments} editable={editable} /></div>
    </div><aside className="refund-panel refund-action-panel min-w-0 space-y-6"><RefundFinanceActions row={row} who={who} deliveryCount={data.delivery.length} />{data.delivery.filter(job => job.error).map(job => <p key={job.id} className="text-xs leading-relaxed text-ui-muted-foreground">{job.error}</p>)}</aside></div>
    <section className="refund-panel refund-history space-y-4" aria-labelledby="history-heading"><h2 id="history-heading" className="text-lg font-semibold">Request history</h2><ol className="divide-y divide-ui-border">{data.events.map(event => <li key={event.id} className="space-y-2 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{refundActions[event.action as keyof typeof refundActions] || event.action}</h3><p className="text-xs text-ui-muted-foreground">{event.actorName} · {formatDateTime(new Date(event.createdAt))}</p></div>{event.note && <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{event.note}</p>}{['submit','approve','pay'].includes(event.action) && <p className="text-xs text-ui-muted-foreground">Requested {euros(typeof event.snapshot.requestedCents === 'number' ? event.snapshot.requestedCents : null)}{typeof event.snapshot.approvedCents === 'number' ? ` · Approved ${euros(event.snapshot.approvedCents)}` : ''}</p>}<Collapsible className="text-sm"><CollapsibleTrigger asChild><Button variant="ghost" className="min-h-11 text-ui-primary">View recorded details</Button></CollapsibleTrigger><CollapsibleContent><dl className="grid gap-3 rounded-ui-md bg-ui-muted p-4 sm:grid-cols-2">{Object.entries({ Customer: event.snapshot.customerName, Site: event.snapshot.clubName, Service: event.snapshot.description, Reason: event.snapshot.reason, 'Payment reference': event.snapshot.paymentReference, 'Refund reference': event.snapshot.paidReference }).filter(([, value]) => typeof value === 'string' && value).map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs text-ui-muted-foreground">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{String(value)}</dd></div>)}</dl></CollapsibleContent></Collapsible></li>)}</ol></section>
  </div>;
}
