// Deliberately synthetic. This module never imports database or environment data.
export const date = '2026-09-14';
export const sites = [{id:'demo-bishopstown',name:'LeisureWorld Bishopstown'},{id:'demo-churchfield',name:'LeisureWorld Churchfield'}];
export const programme = {id:'demo-programme',name:'Water Safety & Fun',sortOrder:0,description:'Building confidence and skills in the water.',archivedAt:null};
export const levels = ['Starfish','Penguins','Turtles','Dolphins'].map((name,i)=>({id:`demo-level-${i}`,name,sortOrder:i,programme,programmeId:programme.id,archivedAt:null}));
export const instructors = [{id:'demo-teacher',name:'Alex Example'},{id:'demo-cover',name:'Robin Example'}];
export const courses = Array.from({length:8},(_,i)=>({id:`demo-class-${i}`,name:null,clubId:sites[i%2].id,club:sites[i%2],dayOfWeek:['MONDAY','TUESDAY','WEDNESDAY','THURSDAY'][i%4],startMinutes:960+30*(i%3),durationMinutes:30,capacity:8,location:i%2?'Lane 1':'Learner Pool',archivedAt:null,levelId:levels[2].id,level:levels[2],instructorId:instructors[i%2].id,instructor:instructors[i%2],_count:{enrolments:i===7?8:4}}));
export const swimmers = ['Avery','Jamie','Casey','Morgan'].map((name,i)=>({id:`demo-swimmer-${i}`,firstName:name,lastName:'Example',memberNumber:`DEMO-${i+1}`,dateOfBirth:new Date('2018-04-06'),joinedOn:new Date('2026-01-05'),status:'ACTIVE',club:sites[0],contactName:'Pat Example',contactPhone:null,contactEmail:'parent@example.invalid',emergencyName:null,emergencyPhone:null,emergencyRelationship:null,medicalNotes:null,notes:null,photoConsent:false,placements:[{levelId:levels[2].id,levelName:'Turtles',programmeName:programme.name}],attendance:[]}));
export const enrolments = [{id:'demo-enrolment',status:'ACTIVE',startedOn:new Date('2026-09-01'),endedOn:null,scheduledEndOn:null,placementReason:null,programmeId:programme.id,programme,levelId:levels[2].id,level:levels[2],course:courses[0]},{id:'demo-waitlist',status:'WAITLISTED',startedOn:new Date('2026-09-05'),endedOn:null,scheduledEndOn:null,placementReason:null,programmeId:programme.id,programme,levelId:levels[2].id,level:levels[2],course:courses[7]}];
export const competencies = ['Float on the back for five seconds','Swim five metres on the front','Enter the water safely'].map((name,i)=>({id:`demo-skill-${i}`,name,description:null,status:i===2?null:'ACHIEVED',assessedOn:i===2?null:new Date(date),assessedByName:i===2?null:'Alex Example',note:null}));
export const progress = [{programmeId:programme.id,programmeName:programme.name,currentLevelId:levels[2].id,graduated:false,levels:[{...levels[2],description:null,competencies,achieved:2,total:3,eligible:false,completedOn:null,completionId:null,completionSnapshot:null,overrideReason:null,confirmedByName:null,isCurrent:true}]}];
export const history = {events:[],next:null,canAudit:true};
export const lines = swimmers.map((swimmer,i)=>({...swimmer,studentId:swimmer.id,levelName:'Turtles',status:i===3?'ABSENT':'PRESENT',note:null,offRoster:false}));
export const assessment = {id:'demo-assessment',programmeId:programme.id,programme:{...programme,levels},typeId:'demo-kind',type:{id:'demo-kind',name:'New swimmers'},date:new Date(date),startMinutes:900,durationMinutes:30,capacity:6,location:'Learner Pool',instructor:instructors[0],instructorId:instructors[0].id,notes:null,cancelledAt:null,club:sites[0]};
export const role = {id:'demo-role',name:'Teaching team',description:'Attendance and competencies for the pool deck.',permissions:['attendance.mark','attendance.cover','progression.assess'],screens:['instructor'],home:'instructor',isSystem:false};
export const billing = {id:'demo-cancellation',courseId:courses[0].id,date,className:'Turtles',startMinutes:960,durationMinutes:30,programmeName:programme.name,location:'Learner Pool',instructorName:instructors[0].name,reason:'Pool unavailable for this session.',cancelledByName:'Alex Example',cancelledAt:date+'T12:00:00Z',attendanceRecorded:0,billingNotifiedAt:null,billingNotifiedByName:null,billingNote:null,swimmers:swimmers.map(s=>({studentId:s.id,swimmerName:`${s.firstName} ${s.lastName}`,memberNumber:s.memberNumber}))};
