import { createRoot } from 'react-dom/client';
import '@fontsource/figtree/latin-400.css';
import '@fontsource/figtree/latin-500.css';
import '@fontsource/figtree/latin-600.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ThemeFlip, ThemeToggle } from '@/components/theme-toggle';
import { TooltipProvider } from '@/components/shadcn/tooltip';
import { AppShell } from '@/components/ui-kit/app-shell';
import { InstructorShell } from '@/components/instructor/instructor-shell';
import { ClubSwitcher } from '@/components/clubs/club-switcher';
import { visibleNavGroups } from '@/lib/nav';
import { ALL_SCREENS } from '@/lib/staff/screens';
import { ScheduleCalendar } from '@/components/today/calendar';
import { StudentDirectory } from '@/components/students/student-directory';
import { SwimmerProfile } from '@/components/students/swimmer-profile';
import { AddSwimmer } from '@/components/students/add-swimmer';
import { ManageProfileEnrolments } from '@/components/students/profile-enrolments';
import { ProfileCompetencies } from '@/components/students/profile-competencies';
import { ClassBrowser } from '@/components/courses/class-browser';
import { ClassDetailView } from '@/components/courses/class-detail';
import { TogetherResults } from '@/components/together/results';
import { RegisterForm } from '@/components/attendance/register-form';
import { RegisterConflict } from '@/components/attendance/register-conflict';
import { DeckChecklist } from '@/components/progression/deck-checklist';
import { StartClass } from '@/components/instructor/start-class';
import { CompleteLevel as InstructorCompleteLevel } from '@/components/instructor/complete-level';
import { BookOntoSession, RecordOutcome } from '@/components/assessments/booking-actions';
import { AddSession } from '@/components/assessments/session-actions';
import { CancelSession } from '@/components/duty/cancel-session';
import { BillingReview } from '@/components/duty/billing-review';
import { AnalyticsDashboard } from '@/components/analytics/dashboard';
import { AddProgramme } from '@/components/curriculum/programme-actions';
import { AddCompetency } from '@/components/curriculum/level-actions';
import { AddPerson } from '@/components/staff/person-actions';
import { EditRole } from '@/components/staff/role-actions';
import { AddClub } from '@/components/clubs/club-actions';
import { ActivityTable } from '@/components/activity-table';
import { ChangePasswordForm } from '@/components/staff/change-password-form';
import { date, sites, programme, levels, instructors, courses, swimmers, enrolments, competencies, progress, history, lines, assessment, role, billing } from './data.mjs';

const scenario = new URLSearchParams(location.search).get('screen') || 'workspace';
window.helpDemo = { swimmers, history };
const access = {edit:true,enrol:true,assess:true,complete:true,override:true,courses:true,assessments:true,audit:true};
const programmeOptions=[{...programme,levels}];
const members=swimmers.slice(0,2).map((s,i)=>({studentId:s.id,name:`${s.firstName} ${s.lastName}`,levelIds:[levels[2+i].id],currentCourseIds:[]}));
const scheduleCourses=courses.filter(c=>c.clubId===sites[0].id&&c.dayOfWeek==='MONDAY').map(c=>({...c,enrolled:4,attendanceTaken:false,cover:null}));
const togetherCourses=[courses[0],{...courses[0],id:'demo-sibling-class',levelId:levels[3].id,level:levels[3],location:'Lane 2'}];
const noop=()=>{};
function Screen() {
  switch (scenario) {
    case 'workspace': case 'site-menu': return <AppShell wordmark="Swimly" userName="Alex Example" userSubtitle="Demonstration account" groups={visibleNavGroups(new Set(ALL_SCREENS))} tools={<ThemeFlip/>} switcher={<ClubSwitcher club={sites[0]} clubs={sites} sidebar/>}><ScheduleCalendar courses={scheduleCourses} assessments={[]} iso={date} todayIso={date} initialNow={950} clubName={sites[0].name} access={{attendance:true,courses:true,assessments:true}}/></AppShell>;
    case 'instructor-menu': case 'instructor-site': case 'instructor-home': return <InstructorShell club={sites[0]} clubs={sites} userName="Alex Example">{null}</InstructorShell>;
    case 'appearance': return <section className="space-y-4"><h1 className="text-2xl font-semibold">Appearance</h1><p>Choose how the app looks on this device.</p><ThemeToggle/></section>;
    case 'password': return <ChangePasswordForm/>;
    case 'directory': return <><h1 className="mb-6 text-2xl font-semibold">Swimmers</h1><StudentDirectory students={swimmers}/></>;
    case 'add-swimmer': return <AddSwimmer/>;
    case 'edit-swimmer': return <AddSwimmer student={swimmers[0]}/>;
    case 'profile': return <SwimmerProfile student={swimmers[0]} enrolments={enrolments} programmes={progress} assessments={[]} targets={courses} history={history} access={access} returnTo="/students" instant={date+'T12:00:00Z'}/>;
    case 'enrol': case 'move': case 'waitlist': case 'end-enrolment': return <ManageProfileEnrolments studentId={swimmers[0].id} active enrolments={enrolments} targets={courses}/>;
    case 'classes': case 'add-class': return <ClassBrowser courses={courses} params={{day:'any'}} todayDay="MONDAY" levels={levels} instructors={instructors} canManage workingSite={sites[0].name}/>;
    case 'class-detail': return <ClassDetailView course={courses[0]} roster={swimmers.map((s,i)=>({id:`roster-${i}`,status:'ACTIVE',startedOn:new Date(date),scheduledEndOn:null,placementReason:null,level:levels[2],programme,student:s}))} targets={courses} levels={levels} instructors={instructors} backHref="/courses" access={{manage:true,admin:true,attendance:true,students:true}}/>;
    case 'schedule': return <ScheduleCalendar courses={scheduleCourses} assessments={[]} iso={date} todayIso={date} initialNow={950} clubName={sites[0].name} access={{attendance:true,courses:true,assessments:true}}/>;
    case 'together': return <><h1 className="mb-6 text-2xl font-semibold">Together</h1><TogetherResults result={{unplaced:[],days:[{day:'MONDAY',together:[{startMinutes:960,courses:togetherCourses}],spread:null}]}} count={2} members={members}/></>;
    case 'start-class': return <StartClass courseId={courses[0].id} date={date} name="Turtles" schedule="16:00–16:30" instructorName="Alex Example" own href="/instructor"/>;
    case 'attendance': return <><h1 className="mb-6 text-2xl font-semibold">Turtles · Attendance</h1><RegisterForm courseId={courses[0].id} date={date} revision="demo-revision" lines={lines} classNote={null} readOnly={false} continueHref="/instructor" teaching/></>;
    case 'save-conflict': return <RegisterConflict saved={{revision:'demo-revision',marks:Object.fromEntries(lines.map(l=>[l.studentId,{status:'ABSENT',note:''}])),note:''}} marks={new Map(lines.map(l=>[l.studentId,{status:l.status,note:''}]))} note="" lines={lines} pending={false} onUseSaved={noop} onReplace={noop}/>;
    case 'competencies': return <><h1 className="mb-6 text-2xl font-semibold">Turtles · Competencies</h1><DeckChecklist courseId={courses[0].id} date={date} levelId={levels[2].id} competencies={competencies} swimmers={swimmers.map((s,i)=>({studentId:s.id,name:`${s.firstName} ${s.lastName}`,offLevel:false,completed:false,marks:Object.fromEntries(competencies.map((c,j)=>[c.id,j===0?'ACHIEVED':i===0?'ACHIEVED':null]))}))} attendance={Object.fromEntries(lines.map(l=>[l.studentId,l.status]))} readOnly={false} doneHref="/instructor" doneLabel="Classes" teaching/></>;
    case 'complete-class': return <InstructorCompleteLevel studentId={swimmers[0].id} studentName="Avery Example" levelId={levels[2].id} levelName="Turtles" courseId={courses[0].id} date={date}/>;
    case 'profile-competencies': return <ProfileCompetencies studentId={swimmers[0].id} programmes={progress} access={access} selectedLevel={levels[2].id}/>;
    case 'complete-level': return <ProfileCompetencies studentId={swimmers[0].id} programmes={progress.map(p=>({...p,levels:p.levels.map(l=>({...l,achieved:3,eligible:true,competencies:l.competencies.map(c=>({...c,status:'ACHIEVED',assessedOn:new Date(date),assessedByName:'Alex Example'}))}))}))} access={access} selectedLevel={levels[2].id}/>;
    case 'assessment-session': return <AddSession programmes={programmeOptions} types={[{id:'demo-kind',name:'New swimmers',programmeId:programme.id}]} instructors={instructors} today={date}/>;
    case 'assessment-booking': return <BookOntoSession session={assessment} taken={2}/>;
    case 'assessment-outcome': return <RecordOutcome booking={{id:'demo-booking',student:swimmers[0],outcomeLevel:null,outcomeNote:null}} session={assessment} variant="button"/>;
    case 'cancel-session': return <CancelSession course={{...courses[0],name:'Turtles',started:false,attendanceRecorded:0}} date={date}/>;
    case 'billing': return <BillingReview row={billing} canNotify/>;
    case 'analytics': return <AnalyticsDashboard data={{siteName:sites[0].name,period:{date,weekStart:'2026-09-14',weekEnd:'2026-09-20',monthStart:'2026-09-01'},swimmers:20,places:24,enrolled:5,withdrawn:2,groups:[{id:programme.id,name:programme.name,levels:levels.map(l=>({...l,count:6,capacity:16,classes:2,percentage:37.5,archived:false}))}],cancellations:{sessions:2,affectedPlaces:8,pending:1,notified:1},daily:Array.from({length:7},(_,i)=>({day:`2026-09-${String(14+i).padStart(2,'0')}`,enrolled:i===0?5:0,withdrawn:i===0?2:0})),canOpenCancellations:true,updatedAt:date+'T12:00:00Z'}}/>;
    case 'programme': return <AddProgramme/>;
    case 'curriculum': return <AddCompetency levelId={levels[2].id} levelName="Turtles"/>;
    case 'staff': return <AddPerson roles={[role]}/>;
    case 'roles': return <EditRole role={role}/>;
    case 'clubs': return <AddClub/>;
    case 'activity': return <><h1 className="mb-6 text-2xl font-semibold">Activity</h1><ActivityTable entries={[{id:'audit-1',summary:'Enrolled Avery Example in Turtles · Monday 16:00',actorName:'Alex Example',action:'enrol',createdAt:new Date(date+'T12:00:00Z')},{id:'audit-2',summary:'Updated Jamie Example’s contact details',actorName:'Robin Example',action:'update',createdAt:new Date(date+'T11:00:00Z')} ]}/></>;
    default: throw new Error(`Unknown screenshot: ${scenario}`);
  }
}
const framed=['workspace','site-menu','instructor-menu','instructor-site','instructor-home'].includes(scenario);
createRoot(document.getElementById('root')).render(<ThemeProvider initialMode="light"><TooltipProvider>{framed?<Screen/>:<main className="mx-auto max-w-6xl p-6 text-sm" data-capture><Screen/></main>}</TooltipProvider></ThemeProvider>);
