import type { HelpArticle } from "./types";

export const CLASS_GUIDES: HelpArticle[] = [
  {
    slug: "find-class", title: "Find a class and see who is enrolled", category: "classes", scopes: ["desk"],
    summary: "Search the weekly timetable by site, level and time, then open the full class details.", keywords: ["classes", "find", "search", "roster", "enrolled", "instructor", "pool", "available"],
    before: ["You need the Classes screen. Opening a swimmer’s profile from the roster also requires the Swimmers screen."],
    steps: [
      { title: "Search Classes", text: "Search by class name, level, programme, site, day, time or instructor. Use Site, Level and Day to narrow the list." },
      { title: "Use the extra filters", text: "More filters includes Programme, Time, Instructor and Pool area. Choose Spaces available, Full or Archived when that is the set you need." },
      { title: "Open the class", text: "Choose its row or View class. Check the weekly schedule, site, pool area, instructor and capacity at the top of the detail page." },
      { title: "Inspect the roster and waitlist", text: "Read Enrolled swimmers and the separate waitlist. The roster includes identifying details and the placement level attached to each enrolment. Available actions depend on your permissions." },
      { title: "Return to the same results", text: "Use the Classes breadcrumb to return with your search, filters and page preserved. Refresh reloads the latest class information." },
    ], result: "You can compare classes and inspect a specific roster without opening a large dropdown.",
    troubleshooting: [{ question: "The availability icon looks different from the attendance status.", answer: "The circled check and X describe available places or a full class. They do not tell you whether attendance has been recorded." }],
    related: ["daily-schedule", "manage-class", "enrol-swimmer"], action: "courses",
  },
  {
    slug: "daily-schedule", title: "Read the daily Schedule", category: "classes", scopes: ["desk"],
    summary: "Choose a day and see its classes, assessments, instructors and available places.", keywords: ["today", "schedule", "calendar", "agenda", "booking sheet", "week", "time"],
    before: ["Check the site selected in the sidebar. Schedule shows one day at that site."],
    steps: [
      { title: "Choose the date", text: "Schedule opens on today. Select a day from the week strip, use the previous or next week controls, or choose Today to return. A week change selects that week’s Monday." },
      { title: "Read the booking sheet", text: "Levels run down the left and class start times across the top. Scroll horizontally for later times. Each booking shows its end time, pool, instructor and places." },
      { title: "Use Agenda for a chronological list", text: "Switch to Agenda to see classes and assessment sessions in time order. Phones use Agenda automatically. Assessment-only days also open this view." },
      { title: "Open the session you need", text: "Depending on your access and the date, a class opens its teaching record or class details. A future class does not open an old attendance register. Assessment links open the assessment session when your role includes Assessments." },
    ], result: "You are looking at the selected day and site, with availability calculated for that day’s enrolments.",
    troubleshooting: [{ question: "Why is the number of places different on another date?", answer: "Enrolment start, end and scheduled-end dates can change who occupies a place on a particular day. The weekly class configuration is current; it is not a historical reconstruction of every timetable edit." }],
    related: ["find-class", "switch-sites", "take-attendance"], action: "calendar",
  },
  {
    slug: "manage-class", title: "Add, edit, archive or restore a class", category: "classes", scopes: ["desk"],
    summary: "Maintain the weekly timetable and distinguish archiving from cancelling one session.", keywords: ["add class", "create", "edit", "archive", "restore", "timetable", "capacity", "teacher", "lane"],
    before: ["You need permission to edit the timetable. Check the working site before adding a class; filtering Classes to another site does not change the working site."],
    steps: [
      { title: "Add the weekly class", text: "In Classes, choose Add class. Check the site named in the dialog, choose a level and fill in the day, start time, duration, capacity, instructor and pool area. A class name is optional." },
      { title: "Save and inspect it", text: "Choose Add class and wait for success. Open the class to verify its site, schedule and capacity." },
      { title: "Edit an existing class", text: "Open its detail page and use Edit. Update the necessary fields, choose Save changes and review the result. Changes affect the weekly class, not just one dated session." },
      { title: "Archive a class that is no longer offered", text: "Use Archive and read the confirmation. Archived classes retain their records and are not available for new enrolments." },
      { title: "Restore when it is offered again", text: "Find the class under Archived and use its restore action. Check that its level, site and timetable are still appropriate." },
    ], result: "The weekly class configuration is updated while historical records remain available.",
    troubleshooting: [{ question: "I only need to cancel today’s lesson.", answer: "Use Cancel session in Duty manager. Archiving changes the ongoing weekly class and is not the same as cancelling one dated occurrence." }],
    related: ["find-class", "cancel-class-session", "manage-curriculum"], action: "courses",
  },
  {
    slug: "start-class", title: "Start your class or take cover", category: "teaching", scopes: ["instructor"],
    summary: "Confirm that you are teaching today’s class before opening its register.", keywords: ["instructor", "start", "cover", "take over", "claim", "pool deck", "my classes", "in progress"],
    before: ["You need the Instructor screen and attendance permission. Starting another instructor’s class also requires permission to take over their class."],
    steps: [
      { title: "Check the site and today’s list", text: "Use My classes for your scheduled classes, or All classes when covering another teacher. You can group the list by time or level." },
      { title: "Choose Start class", text: "Read the class and date in the confirmation. Confirm that you are at the pool and teaching this class. Your own scheduled classes require this confirmation too." },
      { title: "Open the teaching record", text: "Once an instructor has started the class, use Open class. Other authorised instructors can also open it and help. The list shows whether attendance is saved or still needs to be taken." },
      { title: "Return to the list when finished", text: "Use the class-return controls. Your My classes or All classes selection and grouping are retained." },
    ], result: "You are recorded as teaching that class on that date and can open the teaching record within your permissions.",
    troubleshooting: [
      { question: "Another instructor has already started the class.", answer: "Choose Open class to help with attendance or competencies within your permissions. The original start stays recorded, and your saves are attributed to you. If an old page still says In progress, refresh it. Use All classes to find a colleague’s class." },
      { question: "Can I start a cancelled class?", answer: "No. A cancelled session cannot receive a new start or teaching saves. Contact the duty manager if the cancellation needs to be discussed." },
    ], related: ["take-attendance", "record-competencies", "saving-and-connection"], action: "instructor",
  },
  {
    slug: "take-attendance", title: "Take attendance and add a class note", category: "teaching", scopes: ["desk", "instructor"],
    summary: "Record each swimmer’s attendance for the correct class and date, then save it.", keywords: ["register", "attendance", "present", "absent", "late", "note", "paper", "save attendance"],
    before: ["You need attendance permission for the class. Check the date before marking. An unrecorded swimmer starts as absent."],
    steps: [
      { title: "Open your started class", text: "In Instructor, confirm Start class if you have not done so, then choose Open class and the Attendance step. Only the instructor who started the class can save its teaching work here.", scopes: ["instructor"] },
      { title: "Open the correct dated register", text: "Open the teaching record from Schedule or the class’s attendance controls. Select the correct date before copying a paper register. Marking another teacher’s register requires the appropriate permission or offered cover confirmation.", scopes: ["desk"] },
      { title: "Check each swimmer’s attendance", text: "Work through the roster and choose the attendance status that matches what happened. Review Medical information where needed for teaching. Do not leave present swimmers at the default absent status." },
      { title: "Add a class note if needed", text: "Use Class note for information the team should know about this lesson. Check the entire roster before saving." },
      { title: "Save the register", text: "Choose Save and continue to move to competencies, or Save attendance when that button is shown. Wait for the saved result before leaving." },
    ], result: "Attendance and the class note are saved together for the selected class and date.",
    troubleshooting: [{ question: "Someone else saved attendance while I was working.", answer: "Use the comparison the app shows. Review the saved marks before choosing the saved version or deliberately replacing it. A restored draft still needs to be saved." }],
    related: ["start-class", "daily-schedule", "record-competencies", "saving-and-connection"],
  },
  {
    slug: "record-competencies", title: "Record competencies during a class", category: "teaching", scopes: ["desk", "instructor"],
    summary: "Work through the class checklist, mark achievement and save your changes.", keywords: ["competency", "competencies", "skills", "achieved", "not achieved", "checklist", "marks", "assessment", "by swimmer", "mark all"],
    before: ["You need permission to mark competencies and access to this class’s teaching record. In Instructor, you must be the person who started the class."],
    steps: [
      { title: "Save attendance first", text: "Open the class’s Competencies step after reviewing attendance. The checklist separates swimmers who were in today from those who were not." },
      { title: "Choose the competency", text: "Use the competency selector or Previous competency and Next competency to work through the level’s checklist.", scopes: ["desk"] },
      { title: "Mark what was demonstrated", text: "Set each swimmer’s result using the available mark choices. Use Everyone in today achieved only when that is accurate for every swimmer included.", scopes: ["desk"] },
      { title: "Mark one swimmer’s competencies", text: "Tap a swimmer’s name to expand their class-level competencies beneath the row. Mark each result, or use Mark all achieved only when the swimmer has demonstrated every competency. Opening another swimmer keeps your unsaved changes.", scopes: ["instructor"] },
      { title: "Review swimmers who were not in today", text: "Expand Not in today if you need to inspect their existing marks. Do not assume the visible present-swimmer list is the whole roster." },
      { title: "Save the marks", text: "Choose Save marks to save all pending changes across the class. Wait for confirmation, then use Done, back to classes or the return action shown." },
    ], result: "Saved competency marks become part of the swimmer’s shared progress record. Completing a level remains a separate confirmed action.",
    troubleshooting: [{ question: "Why is there no Save marks button?", answer: "You may have no unsaved changes, or the record may be read-only. Check your permissions, whether the class is cancelled or archived, and who started it in Instructor." }],
    related: ["take-attendance", "complete-class-level", "profile-competencies", "saving-and-connection"],
  },
  {
    slug: "complete-class-level", title: "Confirm a level completion from a class", category: "teaching", scopes: ["desk", "instructor"],
    summary: "Record a confirmed milestone after the required competencies have been achieved.", keywords: ["complete", "level", "pass", "graduate", "ready", "milestone", "finish"],
    before: ["You need permission to complete a level. Save competency changes before reviewing who is ready. An instructor must have started the session before teaching records can be saved."],
    steps: [
      { title: "Open the class’s Competencies step", text: "Check the saved marks for the swimmer and review the Ready to complete area when it is available." },
      { title: "Open the completion action", text: "Check the swimmer and level in the dialog. Review any outstanding competencies rather than relying only on the overall count." },
      { title: "Add the relevant note", text: "Enter a completion note if needed. Completing with gaps requires the separate permission and an explanation; it is not an automatic shortcut.", scopes: ["desk"] },
      { title: "Add a note if needed", text: "Use Note (optional) for relevant context. The Instructor completion action is offered when every required competency has been achieved.", scopes: ["instructor"] },
      { title: "Confirm completion", text: "Choose Confirm completion and wait for success. The completion is recorded as its own milestone." },
    ], result: "The level is recorded as completed. The swimmer is not automatically moved to a different weekly class.",
    troubleshooting: [{ question: "The swimmer has achieved every competency but no completion is recorded.", answer: "Achievement and level completion are separate. Someone with completion permission must review the marks and confirm the milestone." }],
    related: ["record-competencies", "complete-level", "move-swimmer", "missing-access"],
  },
  {
    slug: "profile-competencies", title: "Review or edit competencies on a swimmer profile", category: "teaching", scopes: ["desk"],
    summary: "Inspect marks across programmes, make permitted corrections and view a competency’s history.", keywords: ["profile", "competency", "competencies", "progress", "correct mark", "not marked"],
    before: ["Open the swimmer’s profile. Editing requires permission to mark competencies. Archived and completed levels can be read-only."],
    steps: [
      { title: "Open Competencies", text: "Expand the relevant programme and level. The profile shows achieved counts and confirmed completions." },
      { title: "Inspect the current evidence", text: "Read each competency’s mark, assessor and date when available. Use History to inspect its recorded changes when your access allows it." },
      { title: "Make the intended changes", text: "Choose Not marked, Not Achieved or Achieved as appropriate. Review all unsaved edits before leaving the level." },
      { title: "Save the marks", text: "Use the marks save action and wait for confirmation. Changing profile tabs preserves the editing state, but unsaved work still needs a successful save." },
    ], result: "The saved marks update the swimmer’s shared progress, with the changes recorded in their history.",
    troubleshooting: [{ question: "How do I correct a completed level?", answer: "Use the separate completion-correction action if you have permission. Read its consequences before changing a confirmed milestone." }],
    related: ["complete-level", "swimmer-history", "saving-and-connection"], action: "students",
  },
  {
    slug: "complete-level", title: "Complete or correct a level on a swimmer profile", category: "teaching", scopes: ["desk"],
    summary: "Confirm a completed level or take back an incorrect completion with a recorded reason.", keywords: ["level", "completion", "complete", "override", "gaps", "undo", "correct completion", "move up"],
    before: ["Completion requires permission to complete a level. Completing with gaps or taking back a completion requires the additional override permission."],
    steps: [
      { title: "Review the level", text: "In the profile’s Competencies tab, expand the level and check its saved marks." },
      { title: "Confirm an eligible completion", text: "Choose Confirm level completion, add any completion note and choose Confirm completion. If you are allowed to complete with gaps, explain the reason in the required field." },
      { title: "Correct a mistaken completion when necessary", text: "Choose Correct completion on the completed level. Enter the reason and review the Take back completion action before confirming." },
      { title: "Arrange the next class separately", text: "If the swimmer is progressing to a new class, use Manage enrolment and Move class to choose an available destination." },
    ], result: "The milestone or its correction is retained in the swimmer’s history. A class move remains a separate decision.",
    troubleshooting: [{ question: "Why is a reason required?", answer: "An out-of-sequence completion or a correction needs an explanation so the record shows why the normal progression was changed." }],
    related: ["profile-competencies", "move-swimmer", "swimmer-history"], action: "students",
  },
  {
    slug: "assessment-sessions", title: "Create, edit or cancel an assessment session", category: "assessments", scopes: ["desk"],
    summary: "Set up a dated assessment with a programme, assessor and number of places.", keywords: ["assessment", "session", "add", "create", "edit", "cancel", "assessor", "date"],
    before: ["You need the Assessments screen and permission to edit the timetable. Check the working site before adding a session."],
    steps: [
      { title: "Open Assessment setup", text: "In Assessments, choose Assessment setup, then Add a session. Select Programme and Kind, then set Date, Start, Minutes and Places." },
      { title: "Complete the practical details", text: "Choose the pool and assessor and add any notes. Review the site, date and time before choosing Add session." },
      { title: "Inspect or edit the session", text: "In Assessment setup, choose Set up beside the session. Use Edit to change its details, then Save changes. Parent booking publication is managed on this same setup page. View swimmers opens the separate booking roster." },
      { title: "Cancel only when the whole session will not run", text: "Use the session’s cancellation action and read the confirmation. To remove only one swimmer’s booking, use the booking cancellation instead." },
    ], result: "The assessment is available as a dated session, or its cancellation is recorded after confirmation.",
    troubleshooting: [{ question: "The assessment kind I need is missing.", answer: "Kinds of assessment are maintained under the programme. Ask someone with curriculum permission to check the programme’s assessment setup." }],
    related: ["book-assessment", "assessment-outcome", "manage-curriculum"], action: "assessments",
  },
  {
    slug: "book-assessment", title: "Book a swimmer onto an assessment", category: "assessments", scopes: ["desk"],
    summary: "Reserve a place on a session, or cancel an individual booking.", keywords: ["assessment", "book", "booking", "new swimmer", "cancel booking", "places"],
    before: ["The swimmer needs an active profile. You need permission to enrol and move swimmers."],
    steps: [
      { title: "Find the assessment session", text: "Open Assessments → Upcoming assessments and choose View swimmers. Check the programme, site, date, time and available places. Use Past sessions for an earlier assessment." },
      { title: "Choose Book a swimmer", text: "Search for and select the correct swimmer. If they do not yet have a profile, add them under Swimmers first." },
      { title: "Confirm the booking", text: "Choose Book and wait for the result. Check that the swimmer now appears under Booked." },
      { title: "Cancel a booking if the swimmer cannot attend", text: "Use the cancellation action beside that swimmer and confirm Cancel booking. This releases the individual booking, not the whole session." },
    ], result: "The swimmer appears on the assessment’s booking list. A cancelled booking can be made again while the session has room.",
    troubleshooting: [{ question: "The session is full or the booking is rejected.", answer: "Refresh the session and check its capacity and status. Choose another available session if there is no place; the class waitlist option does not apply to assessment bookings." }],
    related: ["add-swimmer", "assessment-outcome", "assessment-sessions"], action: "assessments",
  },
  {
    slug: "assessment-outcome", title: "Record an assessment placement or no-show", category: "assessments", scopes: ["desk", "instructor"],
    summary: "Record where the swimmer belongs in the programme after their assessment.", keywords: ["placement", "outcome", "assessment", "place", "no show", "did not come", "change placement"],
    before: ["You need permission to run assessment sessions. Open the correct session and swimmer booking."],
    steps: [
      { title: "Open today’s assessment", text: "On Instructor, find Assessments today above the class list and choose Open assessment. This shows today’s non-cancelled sessions at your selected site, including sessions with no assessor assigned. My classes and All classes filter weekly classes only. If Open assessment is unavailable, ask a manager for the Run assessment sessions permission.", scopes: ["instructor"] },
      { title: "Record a swimmer who did not attend", text: "Use Did not come beside their booking and confirm it. The desk can then arrange another session." },
      { title: "Place a swimmer who was assessed", text: "Choose Place beside the swimmer. Select the level in the session’s programme and add a note about what you observed." },
      { title: "Save the outcome", text: "Choose Place and wait for confirmation. The placement allows enrolment at that level or a lower one in the same programme without an out-of-sequence reason." },
      { title: "Correct the placement if needed", text: "Use Change placement, review the revised level and note, then save. Arrange any class enrolment as a separate step." },
    ], result: "The assessment and its placement are visible on the swimmer’s record. The outcome does not automatically book a weekly class.",
    troubleshooting: [{ question: "Can an assessment place someone in a different programme?", answer: "The outcome level must belong to the session’s programme. Credit in one programme does not automatically count toward another." }],
    related: ["book-assessment", "assessment-enrolment-follow-up", "enrol-swimmer", "swimmer-history"], action: "assessments",
  },
  {
    slug: "assessment-enrolment-follow-up", title: "Follow up swimmers awaiting enrolment", category: "enrolment", scopes: ["desk"],
    summary: "Find assessed swimmers and class waitlists, then arrange a class place.", keywords: ["awaiting enrolment", "assessed", "follow up", "placement", "waiting", "waitlist", "class place"],
    before: ["Your role needs the Awaiting enrolment screen. Check the site in the sidebar. Enrolling also requires enrolment permission."],
    steps: [
      { title: "Open Awaiting enrolment", text: "Choose Awaiting enrolment directly from the sidebar. It includes assessed swimmers awaiting a place and class waitlists, even without an assessment. The list groups by swimmer and programme, oldest first. Search by name or member number." },
      { title: "Review the placement and family contact", text: "Check the swimmer, member number, any assessed level and each waitlisted class. Open an assessment date or swimmer profile when your access permits it. A waitlist can remain while the swimmer attends another class." },
      { title: "Arrange a class place", text: "For an assessment placement, choose Enrol to find classes at that level across sites. For a waitlisted class with space, choose Enrol from waitlist and confirm. Full or archived classes cannot receive a place here. Capacity is checked again when you confirm." },
      { title: "Check the follow-up is complete", text: "A class place in the same programme resolves the assessment follow-up, including a future start or a class at the other site. Each outstanding waitlist stays visible until promoted, moved or withdrawn through the usual enrolment controls." },
    ], result: "The enrolment is recorded through the usual capacity and audit checks. The assessment remains in the swimmer's history.",
    troubleshooting: [{ question: "Why is an assessed swimmer not in this list?", answer: "Check that they are active and have a recorded placement. Their latest assessment may belong to the other site, or a class enrolment may already have resolved the follow-up." }],
    related: ["assessment-outcome", "enrol-swimmer", "waitlist", "swimmer-history"], action: "awaiting-enrolment",
  },
];
