import type { HelpArticle } from "./types";

export const START_GUIDES: HelpArticle[] = [
  {
    slug: "get-started", title: "Find your way around the app", category: "start", scopes: ["desk"],
    summary: "Know where to find each module, its pages, the site picker and your account.",
    keywords: ["manual", "training", "beginner", "reception", "dashboard", "overview", "navigation", "menu", "page bar", "module", "site", "pool"],
    before: ["Sign in with your staff account. Your role decides which modules, pages and actions you can use."],
    steps: [
      { title: "Check the working site", text: "The site picker is in the tools bar at the top right, beside the swimmer search and your name. On a phone it is the building button. Check it before using Schedule, Duty manager or Analytics." },
      { title: "Move between modules", text: "Your modules are in the bar down the left: Home, Swim school, Refunds, Docs, Training, Rota, HR or Admin, depending on your role. On phones and touch screens they are in the bar along the bottom, with any others under More." },
      { title: "Plan today’s work", text: "Each module’s pages are in the page bar at the top; pages that do not fit are under More. In Swim school, Schedule shows classes and assessments for one day, and Duty manager is today’s operational list." },
      { title: "Find your account", text: "Select your name at the top right to open the account menu. It holds Appearance, Manage account and Sign out." },
      { title: "Keep this guide beside your work", text: "Help opens in a new tab from the bottom of the left bar (under More on phones), so you can read a guide while the form you are working on stays open." },
    ],
    result: "You can choose the right screen for the task and check that you are working at the intended site.",
    troubleshooting: [{ question: "Why does my menu look different from a colleague’s?", answer: "Screens and actions depend on your role. Ask the person who manages staff access if a tool you need is missing." }],
    related: ["switch-sites", "find-swimmer", "find-class", "missing-access"], action: "calendar",
  },
  {
    slug: "switch-sites", title: "Switch site and understand shared records", category: "start", scopes: ["desk", "instructor"],
    summary: "Choose the site you are working at without creating a second swimmer record.",
    keywords: ["site", "pool", "working site", "club", "shared", "location", "facility", "centre"],
    before: ["Each site has its own timetable. Swimmer identity, contacts, curriculum and progress are shared across sites."],
    steps: [
      { title: "Find the site picker", text: "Use the site name in the tools bar at the top right, beside your name. On a phone it is the building button.", scopes: ["desk"] },
      { title: "Find the site picker", text: "Use the site name in the pool deck’s top bar, beside Help.", scopes: ["instructor"] },
      { title: "Choose the site you are working at", text: "Select the site and wait for the page to finish updating. Check the selected name before continuing." },
      { title: "Understand which lists change", text: "Schedule, Duty manager, cancellation follow-up and Analytics use the working site. The Swimmers directory remains shared. Classes and enrolment pickers have their own site filters.", scopes: ["desk"] },
      { title: "Check your classes", text: "My classes and All classes now show the selected site. A swimmer’s saved competencies carry over when they move between sites.", scopes: ["instructor"] },
      { title: "Check a destination’s site", text: "When the desk enrols or moves a swimmer, the destination can be at either site. A class search filter does not change the site in the tools bar.", scopes: ["desk"] },
    ],
    result: "You see the intended timetable while the swimmer keeps one record and their earned progress.",
    troubleshooting: [{ question: "Why can I still see swimmers from the other site?", answer: "That is expected. The same swimmer record is available at both sites. Do not add a duplicate record just because the person is changing pools." }],
    related: ["get-started", "move-swimmer", "start-class"],
  },
  {
    slug: "appearance", title: "Change light or dark appearance", category: "support", scopes: ["desk", "instructor"],
    summary: "Make the app easier to read in bright or dim surroundings.", keywords: ["theme", "dark", "light", "screen", "glare", "colour", "color"],
    before: ["The appearance preference is remembered in the browser you are using."],
    steps: [
      { title: "Open your account menu", text: "Select your name at the top right of the frame. Appearance is at the top of the menu, under your name, role and site.", scopes: ["desk"] },
      { title: "Open your account menu", text: "Select your initials at the right of the pool deck’s top bar. Appearance is under your name, role and site.", scopes: ["instructor"] },
      { title: "Choose System, Light or Dark", text: "The app changes immediately. System follows the device’s own setting, so the app turns dark when the device does." },
      { title: "Use Account for the same choice", text: "Manage account in the same menu also has Appearance, with the same three choices.", scopes: ["desk"] },
    ], result: "The app and the help centre use the selected appearance in this browser.",
    troubleshooting: [{ question: "Why is another tablet using a different appearance?", answer: "Each browser remembers its own preference. Change the appearance on that tablet too." }],
    related: ["saving-and-connection", "missing-access"],
  },
  {
    slug: "account-password", title: "Change your password and sign out", category: "support", scopes: ["desk"],
    summary: "Update your own password and leave a shared device signed out.", keywords: ["login", "sign in", "password", "account", "logout", "log out", "forgotten"],
    before: ["To change your password yourself, you need to know your current password."],
    steps: [
      { title: "Open Account", text: "Select your name at the top right of the frame and choose Manage account." },
      { title: "Enter the password details", text: "Fill in Current password, New password and New password again. Follow the requirements shown beside the field." },
      { title: "Save and check the result", text: "Submit the password change and wait for confirmation. If an error appears, correct the indicated field and try again." },
      { title: "Sign out of a shared device", text: "Open your account menu and choose Sign out when you have finished your work." },
    ], result: "Your password is updated after a successful save. Signing out ends access through the current browser session.",
    troubleshooting: [{ question: "I have forgotten my password. What can I do?", answer: "Ask a staff member who manages accounts to set a new password for you. There is no self-service password-reset email in the app." }],
    related: ["appearance", "missing-access", "manage-staff"], action: "account",
  },
  {
    slug: "missing-access", title: "A screen or button is missing", category: "support", scopes: ["desk", "instructor"],
    summary: "Understand access restrictions, read-only records and unavailable actions.", keywords: ["permission", "role", "missing", "button", "access", "404", "not found", "locked", "disabled"],
    before: ["Your role holds one level in each module. A lower level can let you see a page without changing its records."],
    steps: [
      { title: "Check the record’s state", text: "Archived classes, inactive swimmers, cancelled sessions and completed levels can limit the actions available. Read any message beside the record." },
      { title: "Check the workspace", text: "The pool deck is a separate teaching workspace. It does not include desk administration or swimmer profiles. Another instructor can start a class you also teach; you can both open and help with it." },
      { title: "Ask for the access needed for your task", text: "Tell your manager or an administrator which page you need and what you are trying to do. They can check the level your role has in that module." },
      { title: "Reload after access is updated", text: "Refresh the page and try the task again. If you are signed out, sign back in with your own account." },
    ], result: "You can distinguish a record restriction from missing access and give the administrator a specific request.",
    troubleshooting: [{ question: "A bookmark says the page was not found.", answer: "The record may no longer be available, or your current account may not have access. Start from the app’s menu and ask your manager if the expected screen is absent." }],
    related: ["saving-and-connection", "start-class", "manage-roles"],
  },
  {
    slug: "saving-and-connection", title: "Recover from a failed save or lost connection", category: "support", scopes: ["desk", "instructor"],
    summary: "Know what to do when a save fails, a draft returns or another person changed the record.", keywords: ["error", "offline", "wifi", "internet", "failed", "save", "retry", "conflict", "draft", "support", "help"],
    before: ["A mark on screen is not a saved record until the app confirms it. Draft protection for teaching records is not a guarantee that every form is backed up."],
    steps: [
      { title: "Keep the page open and read the message", text: "Check the error beside the form or save controls. Correct missing information before retrying. If the connection dropped, reconnect first." },
      { title: "Check whether the previous save succeeded", text: "If the app could not confirm a save, inspect the current record or history before repeating an enrolment or move. The request may have reached the server.", scopes: ["desk"] },
      { title: "Check the saved teaching record", text: "If the app could not confirm a save, keep any draft open and check the saved status before retrying. The request may have reached the server.", scopes: ["instructor"] },
      { title: "Review a restored teaching draft", text: "Attendance and competency screens may restore unsaved work on the same browser. Review it, then save again. A ‘not saved’ message means the work still needs to reach the server." },
      { title: "Resolve changes made by someone else", text: "When attendance has changed since you opened it, compare your marks with the saved register. Choose the saved version or deliberately replace it using the offered controls." },
      { title: "Ask for help with the exact problem", text: "If you are still stuck, tell your manager the screen name, the task you were doing and the exact error message. Include whether the problem affects one record or several." },
    ], result: "You recover the work deliberately and can explain any remaining problem clearly.",
    troubleshooting: [
      { question: "The page says this browser cannot keep a backup.", answer: "Keep that tab open until the server confirms the save. Closing it may lose the unsaved attendance or competency marks." },
      { question: "Can I keep working without an internet connection?", answer: "Some teaching drafts can be retained locally, but saving and loading records require a connection. Reconnect, review the draft and wait for a successful save." },
    ], related: ["missing-access", "take-attendance", "record-competencies"],
  },
  {
    slug: "instructor-account", title: "Sign out or get help with your password", category: "support", scopes: ["instructor"],
    summary: "Leave a shared pool-deck device signed out and know who can reset your password.",
    keywords: ["account", "password", "forgot", "login", "sign in", "sign out", "logout", "shared tablet"],
    before: ["Save attendance and competency changes before signing out."],
    steps: [
      { title: "Finish and save your teaching work", text: "Wait for the app to confirm your changes are saved. Resolve any unsaved draft before leaving the class." },
      { title: "Open your account menu", text: "Select your initials at the right of the pool deck’s top bar and choose Sign out. Leave the sign-in screen ready for the next instructor to use their own account." },
      { title: "Ask for a password reset when needed", text: "If you forget your password, ask the staff member who manages accounts to set a new one. There is no password-reset email in the app." },
    ], result: "Your shared device is signed out, or an account manager can help you regain access.",
    troubleshooting: [{ question: "My password still does not work.", answer: "Check the email and password you were given. Ask the account manager to check that your account is active. Do not use another instructor’s login, as saved teaching work is recorded under that account." }],
    related: ["saving-and-connection", "missing-access", "appearance"],
  },
];
