import type { HelpArticle } from "./types";

export const SWIMMER_GUIDES: HelpArticle[] = [
  {
    slug: "find-swimmer", title: "Find a swimmer and update their details", category: "swimmers", scopes: ["desk"],
    summary: "Search one shared directory and check you have the right person before editing.", keywords: ["find", "search", "child", "customer", "member number", "contact", "phone", "medical", "edit"],
    before: ["You need the Swimmers screen. Editing requires permission to add and edit swimmers."],
    steps: [
      { title: "Search Swimmers", text: "Use a name, member number, contact name, email or phone number. The sidebar’s swimmer search is another shortcut to the same records." },
      { title: "Check the identifying details", text: "Compare the member number, age when shown and contact information. Swimmers from both sites are included. Use All, Active or Inactive to adjust the status filter." },
      { title: "Open the profile", text: "Choose the swimmer’s row. The profile brings together their enrolments, progress, attendance, assessment history and details." },
      { title: "Update Details", text: "Open the Details tab and its edit action. Correct the relevant personal, contact, emergency or medical information, then save and check the result." },
    ], result: "The same updated record is available when staff work at either site.",
    troubleshooting: [{ question: "I cannot find someone I know is registered.", answer: "Clear the search, choose All statuses and try their member number or contact details. Check for a spelling difference before creating another record." }],
    related: ["add-swimmer", "swimmer-history", "inactive-swimmers"], action: "students",
  },
  {
    slug: "add-swimmer", title: "Add a new swimmer", category: "swimmers", scopes: ["desk"],
    summary: "Create the swimmer record before booking a class or assessment.", keywords: ["new", "add", "register", "customer", "child", "signup", "sign up"],
    before: ["Search the shared directory first to avoid a duplicate. You need permission to add and edit swimmers."],
    steps: [
      { title: "Open Swimmers and choose Add swimmer", text: "The form opens without leaving the directory." },
      { title: "Enter the swimmer’s information", text: "Complete the required fields and add the contact and other details you have. Follow the form’s member-number and date guidance rather than guessing missing information." },
      { title: "Save the record", text: "Wait for the success message and the new profile to open. If the form reports a duplicate member number, check the existing record." },
      { title: "Choose the next task", text: "Use Manage enrolment to find a class, or open Assessments to book a suitable assessment session." },
    ], result: "The swimmer has one profile shared across sites. Adding the record alone does not enrol them in a class.",
    troubleshooting: [{ question: "The swimmer does not appear in a booking search.", answer: "Check that the new profile saved successfully and that the swimmer is active. Reopen the booking picker and search again." }],
    related: ["find-swimmer", "enrol-swimmer", "book-assessment"], action: "students",
  },
  {
    slug: "swimmer-history", title: "Read a swimmer’s journey and progress", category: "swimmers", scopes: ["desk"],
    summary: "Follow enrolment chapters, competency marks, attendance and assessment placements.", keywords: ["history", "journey", "progress", "contacts", "medical", "assessment", "milestones", "audit"],
    before: ["Open the correct swimmer profile. Detailed change history requires permission to read the activity log."],
    steps: [
      { title: "Start with Journey", text: "Milestones groups the swimmer’s time at the school into enrolment chapters. Expand a chapter to see its class, site, dates and activity. Use the programme filter when the swimmer follows more than one programme." },
      { title: "Inspect individual records", text: "Use Competencies for marks and completed levels, Attendance for lesson records, Assessments for placements, and Details for personal and contact information." },
      { title: "Look up a change", text: "Choose All activity in Journey and use its search, programme and activity-type filters. Where offered, open a competency’s History to inspect changes to that mark." },
      { title: "Read older evidence in context", text: "Some older entries hold a summary or the latest recorded mark, rather than a full sequence of changes. The profile labels these limits. A historical enrolment’s placement level remains attached to that enrolment." },
    ], result: "You can explain where the swimmer is now and how their recorded enrolments and progress developed.",
    troubleshooting: [{ question: "Why does a class’s level differ from an older placement?", answer: "An enrolment keeps its original placement level even if the class is later renamed or assigned another level. Use the chapter’s recorded placement when explaining its history." }],
    related: ["find-swimmer", "profile-competencies", "complete-level"], action: "students",
  },
  {
    slug: "inactive-swimmers", title: "Deactivate or reactivate a swimmer", category: "swimmers", scopes: ["desk"],
    summary: "Change a swimmer’s status while retaining their profile and history.", keywords: ["inactive", "active", "reactivate", "deactivate", "delete", "remove", "returning"],
    before: ["You need permission to add and edit swimmers. Ending one class enrolment is a different task from changing the swimmer’s status."],
    steps: [
      { title: "Open the swimmer’s profile", text: "Search under All or Inactive if the swimmer is not currently active." },
      { title: "Review current places", text: "Check Manage enrolment before changing status. If you only need to end a class place, use Unenrol for that place instead." },
      { title: "Change the status in Edit details", text: "Open Details, choose Edit details and set Status to Active or Inactive. Choose Save details. If the swimmer still has an active class place, end that enrolment before making them inactive." },
      { title: "Check the result", text: "For a returning swimmer, confirm the profile is Active before adding an enrolment or promoting a waitlist place." },
    ], result: "The status changes after a successful save. Existing history stays with the same swimmer record.",
    troubleshooting: [{ question: "Why are enrolment actions unavailable?", answer: "Inactive swimmers cannot receive new enrolments or waitlist promotions. Reactivate the swimmer first if they are returning." }],
    related: ["find-swimmer", "end-enrolment", "enrol-swimmer"], action: "students",
  },
  {
    slug: "enrol-swimmer", title: "Enrol a swimmer in a class", category: "enrolment", scopes: ["desk"],
    summary: "Find an available class at either site and review what happens to any existing places.", keywords: ["enrol", "enrollment", "enrolment", "book", "place", "available", "registration"],
    before: ["The swimmer must be active. You need permission to enrol and move swimmers."],
    steps: [
      { title: "Open Manage enrolment", text: "From the swimmer’s profile, choose Manage enrolment, then Enrol in a class." },
      { title: "Narrow the class list", text: "Choose a site or All sites, then filter by level, day and start time. Search can also match the pool or instructor. Available places only hides full classes." },
      { title: "Select a class and check its details", text: "Read the site, day, full time range and available places. The selected class remains visible at the bottom even if you change the filters." },
      { title: "Explain an out-of-sequence placement if needed", text: "If the swimmer has not earned the destination level, enter a Placement reason. The app checks eligibility when you submit; a reason is kept on the record when required." },
      { title: "Review the enrolment", text: "Choose Review enrolment. If the swimmer already has active places, choose whether to keep them or unenrol from them as part of the new enrolment. Read the confirmation carefully and wait for success." },
    ], result: "The profile shows the new place after a successful save. Capacity and existing places are checked again before the change is made.",
    troubleshooting: [{ question: "The class became full while I was choosing.", answer: "Refresh and choose another available class, or use the explicit waitlist option. A space shown in the list is not reserved until the enrolment succeeds." }],
    related: ["move-swimmer", "waitlist", "switch-sites"], action: "students",
  },
  {
    slug: "move-swimmer", title: "Move a swimmer to another class or site", category: "enrolment", scopes: ["desk"],
    summary: "Compare the destination and confirm a move without losing the swimmer’s history.", keywords: ["move", "transfer", "another site", "Bishopstown", "Churchfield", "change class", "relocate", "switch"],
    before: ["You need permission to enrol and move swimmers. The destination must have a place available."],
    steps: [
      { title: "Choose the place to move", text: "Open the swimmer’s profile, choose Manage enrolment and select Move class beside the correct current place." },
      { title: "Find the destination", text: "The picker starts at the swimmer’s current placement level. Use the site, level, day, time and search filters to find the class you need. The current class is shown above the filters." },
      { title: "Check the selected-class summary", text: "Verify the day, start and end times, and site. Different site highlights a move between sites. Full classes cannot be selected for a move." },
      { title: "Add a placement reason when required", text: "If moving to a level the swimmer has not earned, explain the placement. Earned progress carries between sites." },
      { title: "Review and confirm", text: "Choose Review move, check the source and destination, then choose Confirm move. Use Back to change the selection before confirming." },
    ], result: "The old place ends and the new place opens. Attendance, competency marks and enrolment history stay on the same swimmer profile.",
    troubleshooting: [
      { question: "Why is Review move unavailable?", answer: "Select an available destination first. If it has become full, choose another class. A move cannot send a swimmer directly into a full class." },
      { question: "Can I keep the current class as well?", answer: "Use Enrol in a class instead of Move class, then choose to keep the existing place when prompted." },
    ], related: ["enrol-swimmer", "waitlist", "swimmer-history"], action: "students",
  },
  {
    slug: "waitlist", title: "Join a waitlist or enrol from it", category: "enrolment", scopes: ["desk"],
    summary: "Record interest in a full class and activate the place when there is room.", keywords: ["waitlist", "waiting list", "full", "capacity", "queue", "promote"],
    before: ["You need permission to enrol and move swimmers. A waitlist entry is not an active class place."],
    steps: [
      { title: "Show full classes", text: "In the swimmer’s profile, open Manage enrolment, then Enrol in a class. Turn off Available places only to include full classes." },
      { title: "Choose the full class", text: "Check the site and schedule, then tick Join the waitlist if full. Add a placement reason if the level has not been earned." },
      { title: "Review the booking", text: "Choose Review enrolment. Joining a full class’s waitlist keeps existing active places. Finish any confirmation and check the new waitlist status." },
      { title: "Activate the place when space is available", text: "Open Manage enrolment again and use Enrol from waitlist beside the waiting place. The app checks current capacity before activating it." },
      { title: "Remove an unwanted waiting place", text: "Use Unenrol beside that waitlist entry and confirm the withdrawal. It remains part of the swimmer’s history." },
    ], result: "The swimmer is either waiting for a place or actively enrolled, with the status shown explicitly.",
    troubleshooting: [{ question: "A place opened. Is the swimmer enrolled automatically?", answer: "No. A staff member must use Enrol from waitlist. If another booking takes the last space first, the promotion will be declined." }],
    related: ["enrol-swimmer", "move-swimmer", "end-enrolment"], action: "students",
  },
  {
    slug: "end-enrolment", title: "End an enrolment now or on a future date", category: "enrolment", scopes: ["desk"],
    summary: "Withdraw a class place, record that a class is finished, or schedule the end date.", keywords: ["unenrol", "unenroll", "withdraw", "leave", "cancel place", "end date", "schedule unenrolment", "finished"],
    before: ["You need permission to enrol and move swimmers. Confirm which place should end if the swimmer has several."],
    steps: [
      { title: "Open the place’s end action", text: "From Manage enrolment, choose Unenrol. If an end date is already scheduled, the action is Change end date." },
      { title: "Choose when it ends", text: "For an active place, use When to choose the timing. To end later, select the date option and enter End date. Review the date before saving." },
      { title: "Record the immediate outcome", text: "When ending a place now, add a reason or note. Tick They finished the class only when that accurately describes an active enrolment; a waitlist withdrawal is not class completion." },
      { title: "Confirm the change", text: "Choose Confirm change. A future end date keeps the place active until that date; the date appears beside the enrolment." },
      { title: "Change your mind before the end date", text: "Open Change end date and choose a replacement date or the option to keep the place. Save the change and check the profile." },
    ], result: "The place ends at the selected time while the swimmer’s record and history remain available.",
    troubleshooting: [{ question: "A past end date still appears in an open tab.", answer: "Refresh the page. The app applies scheduled endings when it is used, and an already-open tab may still show its earlier state." }],
    related: ["move-swimmer", "inactive-swimmers", "swimmer-history"], action: "students",
  },
  {
    slug: "sibling-times", title: "Find class times for siblings or a group", category: "enrolment", scopes: ["desk"],
    summary: "Use Together to compare options that have room for each swimmer at their current level.", keywords: ["sibling", "siblings", "sibbling", "family", "brother", "sister", "together", "same time", "friends"],
    before: ["You need the Together screen. It compares current enrolment levels, so each selected swimmer needs a current class level."],
    steps: [
      { title: "Open Together and build the group", text: "Choose Add a child, find the first swimmer, then use Add another. The app may suggest other swimmers who share their contact details." },
      { title: "Check who is included", text: "Review each selected swimmer and their level. Remove anyone who is not part of this search, or use Start again." },
      { title: "Compare the options", text: "Review All starting at the same time and Same day, different times. Check each class’s site, schedule and available places; use Next combinations when more options are available." },
      { title: "Make the bookings separately", text: "Once you have agreed an option, open each swimmer’s enrolment controls to enrol or move them. Searching Together does not reserve spaces or make a group booking." },
    ], result: "You have a set of class options to discuss, with each swimmer’s level taken into account.",
    troubleshooting: [{ question: "No day suits everyone, or someone has no current level.", answer: "Read the explanation, check the selected group and current enrolments, then remove someone to compare the remaining swimmers if useful. You may need separate days or a different class arrangement." }],
    related: ["enrol-swimmer", "move-swimmer", "find-class"], action: "together",
  },
];
