import type { HelpArticle } from "./types";

/** The everyday guides for Home and the Work modules beyond the swim school. Each topic shows
 *  only to people who can open its module (HELP_CATEGORY_SCREENS). Check labels against the
 *  module's components: src/components/{refunds,docs,training,rota,hr}. */
export const MODULE_GUIDES: HelpArticle[] = [
  {
    slug: "home-page", title: "Read your home page", category: "home", scopes: ["desk"],
    summary: "See what needs you today, the day at your site and the quick actions your role has.",
    keywords: ["home", "dashboard", "today", "waiting", "quick actions", "start", "turnfin me", "phone", "my training", "my shifts"],
    before: ["Everyone has a home page. What it shows follows your role’s levels and the sites you work at."],
    steps: [
      { title: "Check what is waiting for you", text: "Waiting for you lists the things that need someone with your access, such as parent updates, practical sign-offs, refunds to decide or qualifications expiring. The number is how many; choose a row to open that list." },
      { title: "Read the day at your site", text: "Classes today and Today at your site summarise the classes, assessments, people on shift and people off at the site in the tools bar. Choose Open schedule for the full day." },
      { title: "Start a common task", text: "Quick actions start the tasks your role does most, such as adding a swimmer, logging a refund request or reporting an absence. Each one opens the module that does it." },
      { title: "Use Turnfin Me for your own things", text: "Your own training, required reading, qualifications, shifts and the HR notes shared with you are in Turnfin Me on your phone, not here. Sign in to it with your work email; it sends you a code." },
    ],
    result: "You can see what needs doing today and go straight to it, while your own records stay on your phone.",
    troubleshooting: [{ question: "Why is my home page different from a colleague’s?", answer: "It follows your role and your sites. Someone with no Refunds level sees no refunds to decide. Ask your manager if a module you need is missing." }],
    related: ["get-started", "switch-sites", "missing-access"],
  },
  {
    slug: "log-refund", title: "Log a refund request", category: "refunds", scopes: ["desk"],
    summary: "Send a customer’s refund request to finance with the details they need to decide it.",
    keywords: ["refund", "money back", "customer", "request", "receipt", "finance", "draft", "reception"],
    before: ["You need the Refunds: Use level. Have the customer’s details, what they paid for, the amount and the original payment reference to hand."],
    steps: [
      { title: "Open Log a refund request", text: "In Refunds, choose Log a refund request at the top right of Refund requests. Home’s quick actions have the same link." },
      { title: "Fill in the customer and the payment", text: "Enter the customer name, choose the site and service, and describe what was purchased. Then add the requested refund, the original payment date and its reference from Legend, a receipt or your payment system, and the reason. Never enter card or bank details." },
      { title: "Save a draft or submit it", text: "Save draft keeps it in My drafts; a draft needs only the site and service, and you must save one to add receipts. When every detail is there, choose Submit to finance." },
      { title: "Follow it in My requests", text: "My requests shows each request you logged and where it is. If finance asks for more information, it comes back to you with their question; answer it and submit again." },
    ],
    result: "Finance can review the request. Every change is recorded with the person and time.",
    troubleshooting: [{ question: "Why can’t I submit yet?", answer: "A submitted request needs the customer name, service description, amount, original payment date and reference, and the reason. The note above the save bar lists them." }],
    related: ["decide-refund", "cancel-class-session"], action: "refunds",
  },
  {
    slug: "decide-refund", title: "Decide a refund request", category: "refunds", scopes: ["desk"],
    summary: "Take responsibility for a request, approve or decline it, then record the payment.",
    keywords: ["refund", "approve", "decline", "finance", "payment", "request information", "pay", "review"],
    before: ["You need the Refunds: Manage level. Nobody decides a request they logged themselves; another finance colleague does."],
    steps: [
      { title: "Open the request", text: "Refund requests shows what needs your team’s action, with figures for Awaiting review, Needs information, Awaiting payment and Refunded. Search by name, member or RF number, then open the request." },
      { title: "Take responsibility for it", text: "Choose Take responsibility so colleagues know you are handling it. Read the customer, service, amount, reason and any receipts." },
      { title: "Approve, decline or ask", text: "Choose Approve refund and confirm the approved amount with a decision note, or Decline request with the reason. If something is missing, choose Request information; the request goes back to whoever logged it." },
      { title: "Record the payment", text: "After paying the refund outside Turnfin, open the approved request and choose Record payment. Enter the refund payment date and method, with an optional note." },
    ],
    result: "The request shows Refunded with the full history of who decided and paid it. Turnfin records the payment; it does not move money.",
    troubleshooting: [{ question: "Why is there no Approve refund button?", answer: "You logged this request, or it is not in review yet. Another finance colleague must review a request you raised." }],
    related: ["log-refund"], action: "refunds",
  },
  {
    slug: "find-document", title: "Find and read a document", category: "docs", scopes: ["desk"],
    summary: "Search the document library for a procedure, policy or emergency plan at your facility.",
    keywords: ["docs", "document", "procedure", "policy", "SOP", "risk assessment", "emergency plan", "library", "read", "required reading"],
    before: ["You need the Docs: Read level. Your own required reading and acknowledgements are in Turnfin Me on your phone."],
    steps: [
      { title: "Search from the Docs overview", text: "Open Docs. Type what you need in Find a document and choose Search, or open Emergency plans for the approved responses at your facility." },
      { title: "Browse the library", text: "Choose Document library in the page bar to see every published document. Use the collections (procedures, operations, policies and risk assessments) and the facility filter to narrow it." },
      { title: "Read the current version", text: "Open the document. The page shows its reference, version, facility and when it was approved, so you know you are reading the version in force." },
    ],
    result: "You read the published version that applies to your facility.",
    troubleshooting: [{ question: "Why can’t I find a document a colleague mentioned?", answer: "It may still be a draft, or written for another facility. Choose All facilities, or ask whoever wrote it whether it has been approved." }],
    related: ["write-document"], action: "docs",
  },
  {
    slug: "write-document", title: "Write a document and send it for approval", category: "docs", scopes: ["desk"],
    summary: "Start from a template, write the document and send it to an independent approver.",
    keywords: ["docs", "write", "draft", "template", "approval", "review", "SOP", "policy", "publish", "approver"],
    before: ["You need the Docs: Write level. Approving needs Can approve documents, and nobody approves their own document."],
    steps: [
      { title: "Start a new document", text: "In Document library choose New document. Choose a template, such as a standard operating procedure, a policy or a risk assessment, then Use this template." },
      { title: "Add the essentials", text: "Enter the title, facility and the other essentials, then choose Create draft and start writing." },
      { title: "Write and save", text: "Write each section in the editor. Your changes save as you go; Save now saves straight away. Drafts are listed under My work." },
      { title: "Send it for approval", text: "Choose Submit for review. Select an independent approver, write a short summary of what changed and choose Send for review. The approver can approve and publish it or request changes." },
    ],
    result: "The approver sees it in their work. Once approved it is published to the library, and required reading is sent to the roles it is aimed at.",
    troubleshooting: [{ question: "No approver is available.", answer: "Approvers must not have edited this version. Ask a Docs manager to give someone else Can approve documents." }],
    related: ["find-document"], action: "docs",
  },
  {
    slug: "assign-training", title: "Assign a training course", category: "training", scopes: ["desk"],
    summary: "Give a course to people at your sites with a due date they see in Turnfin Me.",
    keywords: ["training", "course", "assign", "due date", "e-learning", "refresher", "role", "staff"],
    before: ["You need the Training: Manage level. You can assign only to the people at the sites you cover."],
    steps: [
      { title: "Choose Assign training", text: "Open Training and choose Assign training at the top right of the overview." },
      { title: "Choose the course and the people", text: "Pick the course and an optional Due by date. Tick the people, filter by name, or use Add everyone on a role. People who already have that course open are skipped." },
      { title: "Assign it", text: "Choose Assign. Each person sees the course and its due date in Turnfin Me." },
    ],
    result: "The training appears on the overview as To do, then Overdue if the due date passes.",
    troubleshooting: [{ question: "Why isn’t a course in the list?", answer: "Courses are set up under Courses in the page bar. Add the course there first." }],
    related: ["sign-off-training"], action: "training",
  },
  {
    slug: "sign-off-training", title: "Sign off practical training", category: "training", scopes: ["desk"],
    summary: "Watch someone show a skill in person, then sign it off or send it back with what to practise.",
    keywords: ["training", "sign off", "practical", "trainer", "not yet", "qualification", "assessment"],
    before: ["You need the Training: Trainer level, for people at your sites."],
    steps: [
      { title: "Open Sign-off", text: "Choose Sign-off in the Training page bar. It lists the people who say they are ready, with the course, their note and the due date." },
      { title: "Watch them do it", text: "Arrange a time, for example on their next shift, and watch them show the skill." },
      { title: "Sign it off or send it back", text: "Choose Sign off and add an optional note. If they are not ready, choose Not yet and write what to practise; they see it in Turnfin Me." },
    ],
    result: "Signed-off training counts as done. A course that records a qualification adds it to their record.",
    troubleshooting: [{ question: "Why can’t I sign off my own training?", answer: "A trainer never signs off their own. Ask another trainer." }],
    related: ["assign-training"], action: "training",
  },
  {
    slug: "plan-week", title: "Plan the week", category: "rota", scopes: ["desk"],
    summary: "Add the day's activities, put people on each place, fill the gaps and share the week.",
    keywords: ["rota", "plan", "activity", "week", "gap", "cover", "fill", "copy", "share", "lifeguard", "shift"],
    before: ["You need the Rota: Plan level for your department at the site, or Run. Choose the site in the tools bar first. The site's areas and the activity list are set up in Admin."],
    steps: [
      { title: "Open Plan", text: "In Rota choose Plan. It opens on your department's week; the strip of days counts the gaps on each. Choose a day." },
      { title: "Add the activities", text: "Each area of the site (Main pool, Learner pool) has its own row. Choose the plus on an area, or Add activity: what it is (Lifeguarding, Teaching), the area, when, and how many people at once. Each place becomes a lane. Scroll over the day to zoom in, and drag it to move. Copy fills empty days from an earlier day or week." },
      { title: "Fill the gaps", text: "An amber block is a gap. Choose it and Who can fill it lists everyone, best fit first. Choose the plus beside a name. Warnings such as an expired qualification never stop you." },
      { title: "Share the week", text: "Choose Share week when it is ready. Your staff see their days in Turnfin Me, and hear about any change to them after that." },
    ],
    result: "Each person's shift and breaks are worked out from the activities they are on, under Who's working.",
    troubleshooting: [
      { question: "Why can't I change today?", answer: "Today and earlier days are the duty manager's. They change them from Today, and each change is logged with its reason." },
      { question: "It says there is no room for a break.", answer: "The person is on activities with no free time for the breaks they are owed. Leave a gap in their activities, or have the duty manager arrange it on the day." },
    ],
    related: ["report-absence"], action: "rota",
  },
  {
    slug: "report-absence", title: "Report an absence", category: "rota", scopes: ["desk"],
    summary: "Record that someone is off so their activities show as needing cover.",
    keywords: ["absence", "sick", "off", "absent", "cover", "rota", "return to work", "leave"],
    before: ["You need the Rota: Run level for the person's site. Only people who run the rota see the reason."],
    steps: [
      { title: "Choose Report absence", text: "On Today choose Report absence, or in Rota choose Absences, then Report an absence. Report an absence on Home and the Rota overview opens the same form." },
      { title: "Fill in who and when", text: "Choose who is off, the first day off and the reason. Add the last day off if you know it, and an optional note. Choose Report an absence." },
      { title: "Cover their activities", text: "Their activities in that time show as needing cover and go to the top of Gaps to fill on Today, each with its best fits. Choose the plus beside a name to cover it." },
      { title: "Record the return to work", text: "When they come back, choose Back at work. Talk to them on their first day back, then choose Return to work to record it on their file." },
    ],
    result: "The absence shows under Off now or soon and on their HR file, and their activities show as needing cover.",
    troubleshooting: [{ question: "They are off again with the same thing.", answer: "Report it again. The form asks whether it is the same thing again, so the absences are linked." }],
    related: ["plan-week"], action: "rota",
  },
  {
    slug: "hr-note", title: "Add an HR note", category: "hr", scopes: ["desk"],
    summary: "Record what happened, when and what was agreed, and choose who can read it.",
    keywords: ["hr", "note", "record", "conversation", "personal file", "manager", "shared"],
    before: ["You need the HR: Their team level for people you manage, or Everyone. HR is restricted: you confirm your password and every read is logged."],
    steps: [
      { title: "Open the person’s HR record", text: "In HR, search for the person under People and open their record." },
      { title: "Choose Add note", text: "Choose Add note. Keep to facts: what happened, when and what was agreed." },
      { title: "Choose who can read it", text: "Only me keeps it to you; On their record lets anyone who can read their HR record see it; Shared with them also shows it to the person in Turnfin Me. Choose Add note." },
    ],
    result: "The note is saved against your name on their record. You can withdraw it later with a reason.",
    troubleshooting: [{ question: "Why can’t I see a colleague’s notes?", answer: "Notes marked Only me are private to whoever wrote them." }],
    related: ["hr-review"], action: "hr",
  },
  {
    slug: "hr-review", title: "Run a performance review", category: "hr", scopes: ["desk"],
    summary: "Start a review, write it as a draft and share it with the person to acknowledge.",
    keywords: ["hr", "review", "performance", "appraisal", "probation", "annual", "goals", "acknowledge"],
    before: ["You need the HR: Their team level for people you manage, or Everyone."],
    steps: [
      { title: "Start a review", text: "Open the person’s HR record and choose Start a review. Enter the review period, for example 2026 annual review, and choose Start draft." },
      { title: "Write the review", text: "Fill in the summary, strengths, goals for the next period and overall. It stays a draft that only you and superadmins can see; choose Save draft as you go." },
      { title: "Share it with them", text: "Save your latest changes, then choose Share with and the person’s name. Once shared it cannot be edited. They read it in Turnfin Me and can add a comment when they acknowledge it." },
    ],
    result: "The review shows Awaiting acknowledgement, then Acknowledged once they have read it.",
    troubleshooting: [{ question: "I shared it too early.", answer: "A shared review cannot be edited. Add a note to their record with the correction, or start another review." }],
    related: ["hr-note"], action: "hr",
  },
];
