import type { HelpArticle } from "./types";

export const MANAGEMENT_GUIDES: HelpArticle[] = [
  {
    slug: "cancel-class-session", title: "Cancel today’s class session", category: "operations", scopes: ["desk"],
    summary: "Record a cancellation for one date and keep the affected swimmers available for billing follow-up.",
    keywords: ["duty manager", "closed pool", "cancel lesson", "teacher absent", "refund"],
    before: ["You need access to Duty manager and permission to cancel class sessions."],
    steps: [
      { title: "Check the site and date", text: "Open Duty manager. It shows today’s classes at the working site. Choose the correct site in the sidebar." },
      { title: "Find the class", text: "Search by class, level, instructor, pool or time. Open its quick details to check the class and enrolled swimmers." },
      { title: "Record the reason", text: "Choose Cancel session, enter why the class cannot run and review the date and affected class. Confirm the cancellation." },
      { title: "Arrange the follow-up", text: "Open Cancelled classes to see the saved session and affected swimmers. Follow your club’s process for notifying billing." },
    ],
    result: "Only this dated session is cancelled. The weekly class and its enrolments remain. Existing attendance is kept, and further teaching changes for the cancelled session are blocked.",
    troubleshooting: [
      { question: "Does this refund or message anyone?", answer: "No. The cancellation records what happened. Staff must arrange messages, credits or refunds through the club’s usual process." },
      { question: "I cancelled the wrong session. What now?", answer: "Tell your manager the class, site and date. There is no undo control on this screen. Do not create a replacement class or edit attendance to hide the cancellation." },
    ], related: ["billing-follow-up", "daily-schedule", "manage-class"], action: "duty",
  },
  {
    slug: "billing-follow-up", title: "Follow up on a cancelled class", category: "operations", scopes: ["desk"],
    summary: "Review affected swimmers and record when billing has been told about a cancellation.",
    keywords: ["cancelled classes", "billing notified", "refund", "credit", "handoff"],
    before: ["You need access to Cancelled classes. Recording a billing notification needs its separate permission."],
    steps: [
      { title: "Open the queue", text: "Choose Cancelled classes and check the working site. Awaiting billing includes outstanding cancellations across dates, with the oldest first." },
      { title: "Check the cancellation", text: "Open the session to read its date, class, reason, instructor and affected swimmers. This roster was saved when the session was cancelled." },
      { title: "Tell billing", text: "Contact billing using the club’s usual process. Give them the cancellation details and affected swimmers needed for their follow-up." },
      { title: "Record the handoff", text: "Once billing has been told, enter a handoff note and choose Mark billing notified. Check Billing notified for the saved history." },
    ],
    result: "The cancellation leaves the outstanding queue and keeps the notification record. Mark billing notified records a handoff; it does not send a message or change a bill.",
    troubleshooting: [
      { question: "Why is the swimmer list different from today’s class?", answer: "The saved roster describes the cancelled session. Later enrolments or moves do not rewrite that record." },
      { question: "Why are older dates still here?", answer: "Awaiting billing includes every outstanding cancellation at this site, not just this month." },
    ], related: ["cancel-class-session", "analytics"], action: "cancellations",
  },
  {
    slug: "analytics", title: "Understand the Analytics figures", category: "operations", scopes: ["desk"],
    summary: "Read swimmer totals, class capacity, enrolment activity and cancellations for a site.",
    keywords: ["reports", "dashboard", "statistics", "numbers", "spaces", "occupancy"],
    before: ["Your account needs access to Analytics."],
    steps: [
      { title: "Choose the working site", text: "Open Analytics and check the site selected in the sidebar. The figures describe that site." },
      { title: "Compare swimmers and places", text: "Total swimmers counts distinct currently enrolled swimmers. The level breakdown counts enrolled places against class capacity. A swimmer in two classes can occupy two places while counting as one swimmer." },
      { title: "Read recent activity", text: "The seven-day figures count enrolment and unenrolment actions. Moves, completions and waitlist withdrawals are not counted as new enrolments or unenrolments." },
      { title: "Check cancellations", text: "The cancellation total covers sessions dated in this month. Open Cancelled classes for the outstanding billing queue, which can include older dates. Use Refresh to reload the figures." },
    ],
    result: "You can distinguish customer totals, occupied places and recent changes without treating them as the same measure.",
    troubleshooting: [{ question: "Why doesn’t the cancellation total match the billing queue?", answer: "They answer different questions. Analytics counts sessions in the current month; the queue holds every cancellation still awaiting billing follow-up." }],
    related: ["find-class", "billing-follow-up", "switch-sites"], action: "analytics",
  },
  {
    slug: "manage-curriculum", title: "Manage programmes, levels and competencies", category: "setup", scopes: ["desk"],
    summary: "Maintain the shared curriculum used by classes and swimmer progress at both sites.",
    keywords: ["curriculum", "syllabus", "skills", "order", "archive", "image", "restore"],
    before: ["You need access to Programmes and permission to edit the curriculum. Changes affect both sites."],
    steps: [
      { title: "Open or add a programme", text: "Open Programmes. Choose an existing programme or Add programme, enter its name and optional description, then save. An optional image is saved with the form." },
      { title: "Maintain the levels", text: "Open the programme and choose Add level to append a level. Use the ordering controls to put levels in the order swimmers work through them. Edit a level to update its name, description or image." },
      { title: "Describe the competencies", text: "Within the level, add or edit each competency. Write the skill in What the swimmer has to do, and guidance in Notes for the instructor. Save the change." },
      { title: "Maintain kinds of assessment", text: "On the programme, choose Add a kind of assessment. Enter a name and optional description explaining who the session is for, then choose Add. Existing kinds can be edited or archived; archiving stops new use and keeps existing sessions." },
      { title: "Retire items with care", text: "Use Archive for a programme, level or competency that is no longer offered. Read the confirmation before proceeding. Use Restore if an archived item should be available again." },
    ],
    result: "Classes and teaching checklists use the shared curriculum. Archiving retains recorded history rather than deleting it.",
    troubleshooting: [
      { question: "Do I need a copy for the second site?", answer: "No. Programmes, levels, competencies and swimmer progress are shared. Create the site’s classes using the existing curriculum." },
      { question: "Why is a level missing from a picker?", answer: "Check whether the level or its programme is archived. Archived items are not offered for new placement choices." },
    ], related: ["manage-class", "record-competencies", "complete-level"], action: "programmes",
  },
  {
    slug: "manage-staff", title: "Add staff and manage their accounts", category: "setup", scopes: ["desk"],
    summary: "Create a staff login, change its role, reset a password or deactivate an account.",
    keywords: ["invite", "new teacher", "instructor account", "forgot password", "reset password", "reactivate"],
    before: ["You need access to Staff and permission to manage staff accounts."],
    steps: [
      { title: "Add the person", text: "Open Staff and choose Add person. Enter their name, email, role and temporary password, following the password requirements shown in the form. Save the account." },
      { title: "Give them sign-in details", text: "Share the app address and credentials through your club’s approved process. Creating an account does not send an invitation email." },
      { title: "Change details or access", text: "Use the person’s Edit control to change their name, email or role, then Save changes. Review the role’s screens and permissions if access needs to change." },
      { title: "Reset a forgotten password", text: "Use Set a new password for that person. Enter a password that meets the shown requirements, save it, and give it to the staff member through the club’s approved process." },
      { title: "Deactivate an account that is no longer needed", text: "Choose Deactivate for the person and read the confirmation. Deactivated staff cannot sign in. Their history stays recorded, and the account can be reactivated later." },
    ],
    result: "Staff use individual accounts, and their role determines available screens and actions. Saved access changes apply on subsequent requests.",
    troubleshooting: [
      { question: "Why is the account change blocked?", answer: "The app keeps at least one active person able to manage Staff and at least one able to manage Roles. Give another active account the necessary access before removing the last usable grant." },
      { question: "Why can the new instructor see no classes?", answer: "Check the site, their scheduled classes and their role. Instructor access needs the Instructor screen and attendance permission; covering someone else’s class requires cover permission." },
    ], related: ["manage-roles", "account-password", "missing-access"], action: "staff",
  },
  {
    slug: "manage-roles", title: "Choose what staff can see and do", category: "setup", scopes: ["desk"],
    summary: "Configure role screens, permissions and the page shown after sign-in.",
    keywords: ["permissions", "access", "roles", "administrator", "home page", "landing", "teacher"],
    before: ["You need access to Roles and permission to manage roles. Editing a role affects every staff account assigned to it."],
    steps: [
      { title: "Open or add a role", text: "Open Roles. Add a role or edit an existing one, using a clear name and description." },
      { title: "Choose screens", text: "Select the pages the role should be able to open. Screen access controls navigation; it does not by itself grant permission to change records." },
      { title: "Choose permissions", text: "Read the description beside each permission and select the actions the staff need. Some permissions include narrower ones. Manage staff accounts and Manage roles together grant administrator access to every screen and permission." },
      { title: "Choose the starting page", text: "Under Where they start after signing in, select a suitable home. Make sure the role can open it. For pool-deck staff, grant Instructor and attendance access and choose Instructor as the home." },
      { title: "Save and assign", text: "Save the role, then assign it to staff accounts through Staff. A role can only be deleted when no staff accounts use it; move those accounts to another role first." },
    ],
    result: "The role’s staff get the selected screens and actions. Help and personal account settings do not need a separate screen grant.",
    troubleshooting: [
      { question: "Why does a screen tick not give access?", answer: "Some screens also need a permission: for example, Programmes needs curriculum editing, and Instructor needs attendance. Grant both the screen and its required permission." },
      { question: "Why does the role have more access than I selected?", answer: "A role with both staff management and role management has administrator access automatically. Removing one of those grants returns to the role’s stored selections, subject to the last-access safeguards." },
    ], related: ["manage-staff", "missing-access"], action: "roles",
  },
  {
    slug: "manage-clubs", title: "Add, rename or archive a site", category: "setup", scopes: ["desk"],
    summary: "Manage sites in Clubs while keeping swimmer records and curriculum shared.",
    keywords: ["clubs", "facility", "location", "new site", "restore"],
    before: ["You need access to Clubs and permission to manage clubs."],
    steps: [
      { title: "Add or rename a site", text: "Open Clubs. Choose Add a club, enter the name staff use and choose Add club. To rename a site, use its Rename control and Save changes." },
      { title: "Set up its timetable", text: "Choose the new site in the switcher and add its classes and assessment sessions. Use the existing shared swimmers and curriculum; do not recreate them for the site." },
      { title: "Archive a retired site", text: "Choose Archive for the site and read the confirmation. It leaves the site switcher. Anyone working there moves to an available site on their next visit." },
      { title: "Restore it when needed", text: "Find the archived site in Clubs and use Restore. Its retained records become available through the site again." },
    ],
    result: "Sites have their own timetable, while the customer directory, curriculum, progress and staff remain shared.",
    troubleshooting: [{ question: "Why can’t I archive this site?", answer: "At least one site must remain active. Add or restore another site before archiving the last active one." }],
    related: ["switch-sites", "manage-class", "assessment-sessions"], action: "clubs",
  },
  {
    slug: "activity-log", title: "Find who changed a record", category: "setup", scopes: ["desk"],
    summary: "Read the Activity history and distinguish recorded changes from a swimmer’s current state.",
    keywords: ["audit", "log", "history", "who", "when", "change"],
    before: ["You need access to Activity and permission to read the activity log."],
    steps: [
      { title: "Open Activity", text: "Choose Activity to see recorded changes, newest first." },
      { title: "Read the entry", text: "Check What happened, Who, Action and When. On a narrow screen, the person and time appear below the description." },
      { title: "Go back through the history", text: "Use the page controls to view older entries. To understand one swimmer, open their profile and read the Journey and relevant history tabs as well." },
    ],
    result: "You can trace recorded actions to a person and time. The log explains changes; it does not undo them.",
    troubleshooting: [{ question: "The old entry differs from the record now. Is that an error?", answer: "An entry describes an action at that time. Later edits, moves or corrections can change the current record without replacing the earlier history." }],
    related: ["swimmer-history", "saving-and-connection"], action: "activity",
  },
];
