import type { HelpArticle } from "./types";

export const MANAGEMENT_GUIDES: HelpArticle[] = [
  {
    slug: "cancel-class-session", title: "Cancel today’s class session", category: "operations", scopes: ["desk"],
    summary: "Record a cancellation for one date and keep the affected swimmers available for billing follow-up.",
    keywords: ["duty manager", "closed pool", "cancel lesson", "teacher absent", "refund"],
    before: ["You need access to Duty manager and permission to cancel class sessions."],
    steps: [
      { title: "Check the site and date", text: "Open Duty manager. It shows today’s classes at the working site. Choose the correct site in the tools bar at the top right." },
      { title: "Find the class", text: "Search by class, level, instructor, pool or time. Open its quick details to check the class and enrolled swimmers." },
      { title: "Record the reason", text: "Choose Cancel session, enter why the class cannot run and review the date and affected class. Confirm the cancellation." },
      { title: "Arrange the follow-up", text: "Open Cancelled classes to see the saved session and affected swimmers. Follow your organisation’s process for notifying billing." },
    ],
    result: "Only this dated session is cancelled. The weekly class and its enrolments remain. Existing attendance is kept, and further teaching changes for the cancelled session are blocked.",
    troubleshooting: [
      { question: "Does this refund or message anyone?", answer: "No. The cancellation records what happened. Staff must arrange messages, credits or refunds through your organisation’s usual process." },
      { question: "I cancelled the wrong session. What now?", answer: "Tell your manager the class, site and date. There is no undo control on this screen. Do not create a replacement class or edit attendance to hide the cancellation." },
    ], related: ["billing-follow-up", "daily-schedule", "manage-class"], action: "duty",
  },
  {
    slug: "billing-follow-up", title: "Follow up on a cancelled class", category: "operations", scopes: ["desk"],
    summary: "Review affected swimmers and record when billing has been told about a cancellation.",
    keywords: ["cancelled classes", "billing notified", "refund", "credit", "handoff"],
    before: ["You need access to Cancelled classes. Recording a billing notification needs its separate permission."],
    steps: [
      { title: "Open the queue", text: "Choose Cancelled classes and check the working site. Awaiting billing includes outstanding cancellations across dates, with the oldest first." },
      { title: "Check the cancellation", text: "Open the session to read its date, class, reason, instructor and affected swimmers. This roster was saved when the session was cancelled." },
      { title: "Tell billing", text: "Contact billing using your organisation’s usual process. Give them the cancellation details and affected swimmers needed for their follow-up." },
      { title: "Record the handoff", text: "Once billing has been told, enter a handoff note and choose Mark billing notified. Check Billing notified for the saved history." },
    ],
    result: "The cancellation leaves the outstanding queue and keeps the notification record. Mark billing notified records a handoff; it does not send a message or change a bill.",
    troubleshooting: [
      { question: "Why is the swimmer list different from today’s class?", answer: "The saved roster describes the cancelled session. Later enrolments or moves do not rewrite that record." },
      { question: "Why are older dates still here?", answer: "Awaiting billing includes every outstanding cancellation at this site, not just this month." },
    ], related: ["cancel-class-session", "analytics"], action: "cancellations",
  },
  {
    slug: "analytics", title: "Understand the analytics figures", category: "operations", scopes: ["desk"],
    summary: "Read weekly enrolment activity by person, instructor attendance, swimmers with multiple enrolments, capacity and cancellations for a site.",
    keywords: ["reports", "dashboard", "statistics", "numbers", "spaces", "occupancy", "receptionists", "instructors", "missing attendance", "weekly", "multiple enrolments", "more than one class", "export", "csv", "member id"],
    before: ["Your account needs access to Analytics."],
    steps: [
      { title: "Choose the working site", text: "Open Analytics and check the site in the tools bar at the top right. The figures describe that site." },
      { title: "Compare swimmers and places", text: "Total swimmers counts distinct currently enrolled swimmers. The level breakdown counts enrolled places against class capacity. A swimmer in two classes can occupy two places while counting as one swimmer." },
      { title: "Read this week’s activity", text: "The enrolment and unenrolment figures cover the current Monday–Sunday week in Ireland, including today so far. Moves, completions and waitlist withdrawals are excluded. Future days show a dash." },
      { title: "Compare reception activity", text: "Choose Reception activity to see enrolments and unenrolments by the staff member who recorded them. Search by name and open Daily breakdown for their Monday–Sunday totals. Automatic scheduled withdrawals appear separately when applied." },
      { title: "Check instructor attendance", text: "Choose Instructor attendance. Saved of due compares fully marked attendance with finished classes that have swimmers. Select an instructor, then Needs attendance to find missing or partial registers. Upcoming, cancelled and empty classes are excluded from missed attendance. Saved by shows when a colleague helped." },
      { title: "Find swimmers with more than one enrolment", text: "Choose Multiple enrolments to list swimmers enrolled more than once, waitlist places included. This site covers the working site; All sites counts places across every site you work at. Search by name or member ID, then choose Export CSV to save the list with each swimmer’s member ID." },
      { title: "Check cancellations", text: "The cancellation total covers sessions dated in this month. Open Cancelled classes for the outstanding billing queue, which can include older dates. Use Refresh to reload the figures." },
    ],
    result: "You can distinguish customer totals, occupied places and recent changes without treating them as the same measure.",
    troubleshooting: [{ question: "Why doesn’t the cancellation total match the billing queue?", answer: "They answer different questions. Analytics counts sessions in the current month; the queue holds every cancellation still awaiting billing follow-up." }],
    related: ["find-class", "billing-follow-up", "switch-sites"], action: "analytics",
  },
  {
    slug: "manage-curriculum", title: "Manage programmes, levels and competencies", category: "setup", scopes: ["desk"],
    summary: "Maintain the shared curriculum used by classes and swimmer progress at every site.",
    keywords: ["curriculum", "syllabus", "skills", "order", "archive", "image", "restore"],
    before: ["You need access to Programmes and permission to edit the curriculum. Changes affect every site."],
    steps: [
      { title: "Open or add a programme", text: "Open Programmes. Choose an existing programme or Add a programme, enter its name and optional description, then save. An optional image is saved with the form." },
      { title: "Maintain the levels", text: "Open the programme and choose Add a level to append a level. Use the ordering controls to put levels in the order swimmers work through them. Edit a level to update its name, description or image." },
      { title: "Describe the competencies", text: "Within the level, add or edit each competency. Write the skill in What the swimmer has to do, and guidance in Notes for the instructor. Save the change." },
      { title: "Maintain kinds of assessment", text: "On the programme, choose Add a kind of assessment. Enter a name and optional description explaining who the session is for, then choose Add. Existing kinds can be edited or archived; archiving stops new use and keeps existing sessions." },
      { title: "Retire items with care", text: "Use Archive for a programme, level or competency that is no longer offered. Read the confirmation before proceeding. Use Restore if an archived item should be available again." },
    ],
    result: "Classes and teaching checklists use the shared curriculum. Archiving retains recorded history rather than deleting it.",
    troubleshooting: [
      { question: "Do I need a copy for the second site?", answer: "No. Programmes, levels, competencies and swimmer progress are shared. Create the site’s classes using the existing curriculum." },
      { question: "Why is a level missing from a picker?", answer: "Check whether the level or its programme is archived. Archived items are not offered for new placement choices." },
    ], related: ["manage-class", "record-competencies", "complete-level"], action: "programmes",
  },
  {
    slug: "manage-staff", title: "Add staff and manage their accounts", category: "setup", scopes: ["desk"],
    summary: "Create a staff login, change its role, reset a password or deactivate an account.",
    keywords: ["invite", "new teacher", "instructor account", "forgot password", "reset password", "reactivate"],
    before: ["You need access to Staff and permission to manage staff accounts."],
    steps: [
      { title: "Add the person", text: "Open Staff and choose Add a person. Enter their name, email, role and temporary password, following the password requirements shown in the form. Save the account." },
      { title: "Give them sign-in details", text: "Share the app address and credentials through your organisation’s approved process. Creating an account does not send an invitation email." },
      { title: "Change details or access", text: "Use the person’s Edit control to change their name, email or role, then Save changes. If they need different access, give them another role or change the role’s levels in Roles." },
      { title: "Reset a forgotten password", text: "Use Set a new password for that person. Enter a password that meets the shown requirements, save it, and give it to the staff member through your organisation’s approved process." },
      { title: "Deactivate an account that is no longer needed", text: "Choose Deactivate for the person and read the confirmation. Deactivated staff cannot sign in. Their history stays recorded, and the account can be reactivated later." },
    ],
    result: "Staff use individual accounts, and their role’s levels decide which modules, pages and actions they have. Saved access changes apply on subsequent requests.",
    troubleshooting: [
      { question: "Why is the account change blocked?", answer: "The app keeps at least one active person able to manage Staff and at least one able to manage Roles. Give another active account the necessary access before removing the last usable grant." },
      { question: "Why can the new instructor see no classes?", answer: "Check the sites they work at, their scheduled classes and their role. The pool deck needs a Pool deck level on the role; Lead lets them open colleagues’ classes too." },
    ], related: ["manage-roles", "account-password", "missing-access"], action: "staff",
  },
  {
    slug: "manage-roles", title: "Choose what staff can see and do", category: "setup", scopes: ["desk"],
    summary: "Give a role one level in each module and name the home page its people see first.",
    keywords: ["permissions", "access", "roles", "levels", "administrator", "home page", "landing", "teacher", "module"],
    before: ["You need Admin: Manage. Editing a role affects every staff account assigned to it. Only a superadmin can give HR."],
    steps: [
      { title: "Open or add a role", text: "In Admin, open Roles. Choose Add a role, or the edit button beside an existing role. Give it a clear name, a home page name such as Front of House, and an optional description." },
      { title: "Choose a level in each module", text: "Under What this role can do in each module, pick None or a level for Swim school, Pool deck, Refunds, Docs, Training, Rota, HR and Admin. Each level includes the ones before it; the line under the row says what it allows. Give the lowest level that lets the job get done." },
      { title: "Add any extra permissions", text: "Some levels offer a tick for one extra permission, such as cancelling classes or approving documents. Tick it only when the job needs it. Admin: Manage gives Manage in every module except HR." },
      { title: "Decide where they can sign in", text: "Tick Can work away from the centre’s computers only when the role needs to use Turnfin on a phone or another device that is not registered." },
      { title: "Save and assign", text: "Save the role, then give it to people in Staff. Each person holds one role. A role can only be deleted when nobody uses it; move those people to another role first." },
    ],
    result: "Everyone on the role gets the chosen levels at their next page load. Help and their own account settings need no level.",
    troubleshooting: [
      { question: "Why can’t I change the HR level?", answer: "HR is restricted. Only a superadmin can give HR or change a role that holds it." },
      { question: "Why does the editor say the role uses older permission settings?", answer: "The role was set up before levels. Saving switches it to the levels shown; read the note to see whether it gains anything." },
    ], related: ["manage-staff", "missing-access"], action: "roles",
  },
  {
    slug: "manage-clubs", title: "Add, rename or archive a site", category: "setup", scopes: ["desk"],
    summary: "Add, rename and archive sites while swimmer records and curriculum stay shared.",
    keywords: ["sites", "clubs", "facility", "location", "new site", "restore"],
    before: ["You need Admin access to manage sites."],
    steps: [
      { title: "Add or rename a site", text: "Open Sites. Choose Add a site, enter the name staff use and choose Add a site at the bottom. To rename a site, use its Rename control and Save changes." },
      { title: "Set up its timetable", text: "Choose the new site in the site picker and add its classes and assessment sessions. Use the existing shared swimmers and curriculum; do not recreate them for the site." },
      { title: "Archive a retired site", text: "Choose Archive for the site and read the confirmation. It leaves the site picker. Anyone working there moves to an available site on their next visit." },
      { title: "Restore it when needed", text: "Find the archived site in Sites and use Restore. Its retained records become available through the site again." },
    ],
    result: "Sites have their own timetable, while the customer directory, curriculum, progress and staff remain shared.",
    troubleshooting: [{ question: "Why can’t I archive this site?", answer: "At least one site must remain active. Add or restore another site before archiving the last active one." }],
    related: ["switch-sites", "manage-class", "assessment-sessions"], action: "clubs",
  },
  {
    slug: "activity-log", title: "Find who changed a record", category: "setup", scopes: ["desk"],
    summary: "Read the Activity history and distinguish recorded changes from a swimmer’s current state.",
    keywords: ["audit", "log", "history", "who", "when", "change"],
    before: ["You need access to Activity and permission to read the activity log."],
    steps: [
      { title: "Open Activity", text: "Choose Activity to see recorded changes, newest first." },
      { title: "Read the entry", text: "Check What happened, Who, Action and When. On a narrow screen, the person and time appear below the description." },
      { title: "Go back through the history", text: "Use the page controls to view older entries. To understand one swimmer, open their profile and read the Journey and relevant history tabs as well." },
    ],
    result: "You can trace recorded actions to a person and time. The log explains changes; it does not undo them.",
    troubleshooting: [{ question: "The old entry differs from the record now. Is that an error?", answer: "An entry describes an action at that time. Later edits, moves or corrections can change the current record without replacing the earlier history." }],
    related: ["swimmer-history", "saving-and-connection"], action: "activity",
  },
];
